import assert from "node:assert/strict";
import test from "node:test";
import { createDraftVoyageEncounterDefaults } from "../../../scripts/voyage/domain/defaults.js";
import { applyVoyageEncounterPendingCheckPreparation } from "../../../scripts/voyage/domain/pending-checks.js";
import { applyVoyageEncounterPendingCheckResult } from "../../../scripts/voyage/domain/resolution-results.js";
import { analyzeVoyageEncounterActionOutcomes } from "../../../scripts/voyage/domain/action-outcome-interpretation.js";

const KEYS = ["structurallyValid","definitionsValid","pendingChecksValid","resolutionComplete","active","consequences","readyForInterpretation","actionCount","interpretedActionCount","checkActionCount","noRollActionCount","intentCount","actions","intents","errors","warnings"];
const ACTION_KEYS = ["sequence","stationId","actionId","mode","branch","riskBidId","branchEffectIds","riskBidEffectIds","intentIds"];
const INTENT_KEYS = ["intentId","encounterId","stageId","roundNumber","sequence","stationId","actionId","mode","branch","riskBidId","activationSource","referenceIndex","effectId","intentType","timing","visibility","target","selectedTarget","payload"];
const rule = (effectId, payload = { nested: { value: 1 } }) => ({ effectId, intentType: "discovery", timing: "consequences", visibility: "public", target: { kind: "selected-target" }, payload });
function state(actions = [], selections = {}) { return { ...createDraftVoyageEncounterDefaults(), encounterId: "encounter|x", definitionId: "definition", lifecycleState: "active", revision: 1, primaryShip: { actorId: "ship" }, currentStage: { stageId: "stage|x" }, roundNumber: 2, phase: "consequences", availableStations: [{ stationId: "captain", selectionRequired: false, actions }], selections, targets: { captain: { id: "chosen", nested: { value: 1 } } }, successConditions: [{ conditionId: "success" }], failureConditions: [{ conditionId: "failure" }] }; }
function noRoll(effectId = "effect|x") { return { actionId: "wait", outcomeDefinition: { effectRules: [rule(effectId)], branches: { "no-roll": [effectId] } } }; }
function checkAction() { return { actionId: "check", check: { source: { kind: "character", uuid: "Actor.captain" }, statisticOptions: ["diplomacy"], dcSource: { kind: "fixed", value: 20 }, secrecy: "public" }, outcomeDefinition: { effectRules: ["critical-failure","failure","success","critical-success"].map((slug) => rule(slug)), branches: Object.fromEntries(["critical-failure","failure","success","critical-success"].map((slug) => [slug, [slug]])) } }; }
function resolved(slug) { let encounter = state([checkAction()], { captain: { stationId: "captain", actionId: "check" } }); encounter.phase = "resolution"; const prepared = applyVoyageEncounterPendingCheckPreparation(encounter, { pendingCheckIds: [{ sequence: 0, pendingCheckId: "pending" }] }); assert.equal(prepared.ok, true); const degree = { "critical-failure": 0, failure: 1, success: 2, "critical-success": 3 }[slug]; const result = applyVoyageEncounterPendingCheckResult(prepared.nextState, { ok: true, status: "rolled", pendingCheckId: "pending", sequence: 0, sourceKind: "character", sourceUuid: "Actor.captain", statisticSlug: "diplomacy", dc: 20, rollMode: "public", result: { total: 20, degreeOfSuccess: degree, degreeOfSuccessSlug: slug }, errors: [], warnings: [] }); assert.equal(result.ok, true); result.nextState.phase = "consequences"; return result.nextState; }
function atomic(report) { assert.equal(report.readyForInterpretation, false); assert.equal(report.interpretedActionCount, 0); assert.equal(report.intentCount, 0); assert.deepEqual(report.actions, []); assert.deepEqual(report.intents, []); }

test("reports exact empty-plan contract", () => { const report = analyzeVoyageEncounterActionOutcomes(state()); assert.deepEqual(Object.keys(report), KEYS); assert.equal(report.readyForInterpretation, true); assert.equal(report.actionCount, 0); assert.equal(report.intentCount, 0); });
test("interprets a no-roll branch with exact isolated shapes", () => { const encounter = state([noRoll()], { captain: { stationId: "captain", actionId: "wait" } }); const before = structuredClone(encounter); const report = analyzeVoyageEncounterActionOutcomes(encounter); assert.equal(report.readyForInterpretation, true); assert.deepEqual(Object.keys(report.actions[0]), ACTION_KEYS); assert.deepEqual(Object.keys(report.intents[0]), INTENT_KEYS); assert.equal(report.actions[0].branch, "no-roll"); assert.equal(report.intents[0].activationSource, "branch"); assert.deepEqual(encounter, before); for (const key of ["total","dc","degreeOfSuccess","statisticSlug","rollMode","pendingCheckId","pendingCheckIndex"]) { assert.equal(Object.hasOwn(report.actions[0], key), false); assert.equal(Object.hasOwn(report.intents[0], key), false); } });
test("selects each normalized check degree branch", () => { for (const slug of ["critical-failure","failure","success","critical-success"]) { const report = analyzeVoyageEncounterActionOutcomes(resolved(slug)); assert.equal(report.readyForInterpretation, true); assert.equal(report.actions[0].branch, slug); assert.equal(report.intents[0].branch, slug); } });
test("uses accepted sequence order and preserves sparse reference indexes", () => { const first = noRoll("first"); first.resolutionPriority = 5; const second = noRoll("second"); second.actionId = "later"; second.resolutionPriority = 1; second.outcomeDefinition.effectRules = [rule("skip"), rule("second")]; second.outcomeDefinition.branches["no-roll"] = [,"second"]; const encounter = state([first, second], { captain: { stationId: "captain", actionId: "later" } }); const report = analyzeVoyageEncounterActionOutcomes(encounter); assert.deepEqual(report.actions.map((entry) => entry.actionId), ["later"]); assert.equal(report.intents[0].referenceIndex, 1); });
test("intent identity is deterministic and delimiter safe", () => { const a = analyzeVoyageEncounterActionOutcomes(state([noRoll("a|b")], { captain: { stationId: "captain", actionId: "wait" } })); const b = analyzeVoyageEncounterActionOutcomes(state([noRoll("a|b")], { captain: { stationId: "captain", actionId: "wait" } })); assert.equal(a.intents[0].intentId, b.intents[0].intentId); assert.equal(a.intents[0].intentId, 'arcflight-intent:["encounter|x","stage|x",2,0,"branch",0,"a|b"]'); });
test("fails atomically for lifecycle, phase, missing and unresolved checks, invalid pending data, and definitions", () => { const lifecycle = state([noRoll()], { captain: { stationId: "captain", actionId: "wait" } }); lifecycle.lifecycleState = "paused"; atomic(analyzeVoyageEncounterActionOutcomes(lifecycle)); const phase = state([noRoll()], { captain: { stationId: "captain", actionId: "wait" } }); phase.phase = "resolution"; atomic(analyzeVoyageEncounterActionOutcomes(phase)); const missing = state([checkAction()], { captain: { stationId: "captain", actionId: "check" } }); atomic(analyzeVoyageEncounterActionOutcomes(missing)); const unresolved = resolved("success"); unresolved.pendingChecks[0].status = "pending"; unresolved.pendingChecks[0].result = null; atomic(analyzeVoyageEncounterActionOutcomes(unresolved)); const invalidPending = resolved("success"); invalidPending.pendingChecks[0].result.extra = true; atomic(analyzeVoyageEncounterActionOutcomes(invalidPending)); const invalidDefinition = state([noRoll()], { captain: { stationId: "captain", actionId: "wait" } }); invalidDefinition.availableStations[0].actions[0].outcomeDefinition.branches["no-roll"] = ["missing"]; atomic(analyzeVoyageEncounterActionOutcomes(invalidDefinition)); });
test("deeply isolates all returned mutable values", () => { const encounter = state([noRoll()], { captain: { stationId: "captain", actionId: "wait" } }); const first = analyzeVoyageEncounterActionOutcomes(encounter); const sibling = structuredClone(first.intents[0]); first.actions[0].branchEffectIds.push("bad"); first.actions[0].riskBidEffectIds.push("bad"); first.actions[0].intentIds.push("bad"); first.intents[0].target.kind = "changed"; first.intents[0].selectedTarget.nested.value = 9; first.intents[0].payload.nested.value = 9; assert.equal(encounter.targets.captain.nested.value, 1); assert.equal(sibling.target.kind, "selected-target"); assert.equal(sibling.selectedTarget.nested.value, 1); assert.equal(sibling.payload.nested.value, 1); const later = analyzeVoyageEncounterActionOutcomes(encounter); assert.deepEqual(later.actions[0].branchEffectIds, ["effect|x"]); assert.equal(later.intents[0].payload.nested.value, 1); });
