import assert from "node:assert/strict";
import test from "node:test";
import { createDraftVoyageEncounterDefaults } from "../../../scripts/voyage/domain/defaults.js";
import { analyzeVoyageEncounterActionOutcomeDefinitions, validateVoyageEncounterActionOutcomeDefinitions } from "../../../scripts/voyage/domain/consequence-rules.js";
import { VOYAGE_ENCOUNTER_LIFECYCLE_STATES as LIFE, VOYAGE_ROUND_PHASES as PHASES } from "../../../scripts/voyage/domain/constants.js";
function state(action = { actionId: "wait" }) { return { ...createDraftVoyageEncounterDefaults(), encounterId:"e", definitionId:"d", lifecycleState:LIFE.ACTIVE, revision:0, primaryShip:{actorId:"s"}, currentStage:{stageId:"s"}, roundNumber:1, phase:PHASES.CONSEQUENCES, availableStations:[{stationId:"captain",actions:[action]}], successConditions:[{conditionId:"x"}], failureConditions:[{conditionId:"y"}] }; }
test("omitted definitions normalize no-roll actions", () => { const r=analyzeVoyageEncounterActionOutcomeDefinitions(state()); assert.deepEqual(r.actions[0].branches,{"no-roll":[]}); assert.equal(r.readyForInterpretation,true); });
test("validates local rule references and warns on unreferenced rules", () => { const a={actionId:"wait",outcomeDefinition:{effectRules:[{effectId:"x",intentType:"discovery",timing:"consequences",visibility:"public",target:{kind:"encounter"},payload:{delta:1}}],branches:{"no-roll":[]}}}; const r=validateVoyageEncounterActionOutcomeDefinitions(state(a)); assert.equal(r.valid,true); assert.equal(r.warnings[0].code,"unreferenced-effect-rule"); });
test("rejects unsafe payload values", () => { const a={actionId:"wait",outcomeDefinition:{effectRules:[{effectId:"x",intentType:"discovery",timing:"consequences",visibility:"public",target:{kind:"encounter"},payload:{bad:undefined}}],branches:{"no-roll":[]}}}; assert.equal(validateVoyageEncounterActionOutcomeDefinitions(state(a)).valid,false); });
test("counts actual sparse action paths and preserves validity invariant", () => { const a={actionId:"a"}; const b={actionId:"b",outcomeDefinition:{effectRules:"bad",branches:{"no-roll":[]}}}; const actions=[a,,b]; const s=state(a); s.availableStations=[{stationId:"one",actions},{stationId:"two",actions:[{actionId:"c"}]}]; const r=analyzeVoyageEncounterActionOutcomeDefinitions(s); assert.equal(r.actionCount,3); assert.equal(r.validActionCount,2); assert.equal(r.invalidActionCount,1); assert.equal(r.validActionCount+r.invalidActionCount,r.actionCount); });
test("isolates targets payloads branches and risk bid arrays", () => { const action={actionId:"x",outcomeDefinition:{effectRules:[{effectId:"e",intentType:"track-change",timing:"consequences",visibility:"public",target:{kind:"track",targetId:"p"},payload:{n:1}}],branches:{"no-roll":["e"]}},riskBidOptions:[{riskBidId:"r",rewardEffectIds:["e"]}]}; const s=state(action); const r=analyzeVoyageEncounterActionOutcomeDefinitions(s); r.actions[0].effectRules[0].target.targetId="x"; r.actions[0].effectRules[0].payload.n=9; r.actions[0].branches["no-roll"][0]="x"; r.actions[0].riskBidOptions[0].rewardEffectIds[0]="x"; assert.equal(action.outcomeDefinition.effectRules[0].target.targetId,"p"); assert.equal(action.outcomeDefinition.effectRules[0].payload.n,1); assert.equal(action.outcomeDefinition.branches["no-roll"][0],"e"); assert.equal(action.riskBidOptions[0].rewardEffectIds[0],"e"); });
test("reports exact missing reference and warning paths", () => { const action={actionId:"x",outcomeDefinition:{effectRules:[{effectId:"unused",intentType:"discovery",timing:"consequences",visibility:"public",target:{kind:"encounter"},payload:{}}],branches:{"no-roll":["missing"]}}}; const r=analyzeVoyageEncounterActionOutcomeDefinitions(state(action)); assert.ok(r.errors.some(x=>x.path.endsWith('branches.no-roll[0]'))); assert.ok(r.warnings.some(x=>x.path.endsWith('effectRules[0].effectId'))); });
test("rejects nonenumerable and accessor exact fields without reading getters", () => { const action={actionId:"x",outcomeDefinition:{effectRules:[],branches:{"no-roll":[]}}}; Object.defineProperty(action.outcomeDefinition,"extra",{value:true}); const r=validateVoyageEncounterActionOutcomeDefinitions(state(action)); assert.equal(r.valid,false); let reads=0; const target={kind:"encounter"}; Object.defineProperty(target,"bad",{get(){reads++;throw Error();}}); action.outcomeDefinition.effectRules=[{effectId:"e",intentType:"discovery",timing:"consequences",visibility:"public",target,payload:{}}]; const q=validateVoyageEncounterActionOutcomeDefinitions(state(action)); assert.equal(reads,0); assert.ok(q.errors.some(x=>x.code==="unexpected-effect-target-field")); });
test("validates all target shapes and rejects non-ID target IDs", () => { for (const kind of ["encounter","current-stage","primary-ship","source-station","selected-target"]) { const a={actionId:"x",outcomeDefinition:{effectRules:[{effectId:"e",intentType:"discovery",timing:"consequences",visibility:"public",target:{kind},payload:{}}],branches:{"no-roll":["e"]}}}; assert.equal(validateVoyageEncounterActionOutcomeDefinitions(state(a)).valid,true,kind); a.outcomeDefinition.effectRules[0].target.targetId="bad"; assert.ok(validateVoyageEncounterActionOutcomeDefinitions(state(a)).errors.some(x=>x.code==="unexpected-effect-target-id")); } for (const kind of ["track","participant","station"]) { const a={actionId:"x",outcomeDefinition:{effectRules:[{effectId:"e",intentType:"discovery",timing:"consequences",visibility:"public",target:{kind,targetId:"id"},payload:{}}],branches:{"no-roll":["e"]}}}; assert.equal(validateVoyageEncounterActionOutcomeDefinitions(state(a)).valid,true,kind); } });
test("rejects unsafe and duplicate local effect references", () => { const a={actionId:"x",outcomeDefinition:{effectRules:[{effectId:"e",intentType:"discovery",timing:"consequences",visibility:"public",target:{kind:"encounter"},payload:{}}],branches:{"no-roll":["e","e","__proto__"]}}}; const codes=validateVoyageEncounterActionOutcomeDefinitions(state(a)).errors.map(x=>x.code); assert.ok(codes.includes("duplicate-effect-reference")); assert.ok(codes.includes("unsafe-effect-reference")); });
test("rejects symbol-keyed payload fields without mutation", () => { const payload={}; const symbol=Symbol("hidden"); payload[symbol]=1; const action={actionId:"x",outcomeDefinition:{effectRules:[{effectId:"e",intentType:"discovery",timing:"consequences",visibility:"public",target:{kind:"encounter"},payload}],branches:{"no-roll":["e"]}}}; const report=validateVoyageEncounterActionOutcomeDefinitions(state(action)); assert.ok(report.errors.some(x=>x.code==="invalid-effect-payload")); assert.equal(payload[symbol],1); });
test("Risk Bid accessors are rejected without invocation", () => { const option={riskBidId:"bid"}; let reads=0; Object.defineProperty(option,"rewardEffectIds",{get(){reads++;throw Error("unsafe");}}); const action={actionId:"x",riskBidOptions:[option]}; const report=validateVoyageEncounterActionOutcomeDefinitions(state(action)); assert.equal(reads,0); assert.ok(report.errors.some(x=>x.code==="outcome-data-read-failed")); });
