import assert from "node:assert/strict";
import test from "node:test";
import { createDraftVoyageEncounterDefaults, clonePlainData } from "../../../scripts/voyage/domain/defaults.js";
import { VOYAGE_ENCOUNTER_LIFECYCLE_STATES as STATES, VOYAGE_ROUND_PHASES } from "../../../scripts/voyage/domain/constants.js";
import { validateVoyageEncounterRiskBids, applyVoyageEncounterRiskBidSelection, applyVoyageEncounterRiskBidChange, applyVoyageEncounterRiskBidClear } from "../../../scripts/voyage/domain/risk-bids.js";
import { applyVoyageEncounterStationActionSelectionChange, applyVoyageEncounterStationActionSelectionClear } from "../../../scripts/voyage/domain/station-selection.js";
function state() { return { ...createDraftVoyageEncounterDefaults(), encounterId: "risk", definitionId: "d", lifecycleState: STATES.ACTIVE, revision: 3, primaryShip: { actorId: "ship" }, currentStage: { stageId: "s" }, roundNumber: 1, phase: VOYAGE_ROUND_PHASES.CREW_PLANNING, availableStations: [{ stationId: "navigator", actions: [{ actionId: "thread", riskBidOptions: [{ riskBidId: "close", note: "opaque" }, { riskBidId: "bold" }] }, { actionId: "safe", riskBidOptions: [{ riskBidId: "close" }] }] }], selections: { navigator: { stationId: "navigator", actionId: "thread" } }, successConditions: [{ conditionId: "ok" }], failureConditions: [{ conditionId: "no" }] }; }
test("validates optional and action-coupled risk bids without mutation", () => { const source = state(); const before = clonePlainData(source); assert.equal(validateVoyageEncounterRiskBids(source).valid, true); source.riskBids.navigator = { stationId: "navigator", actionId: "thread", riskBidId: "close" }; assert.equal(validateVoyageEncounterRiskBids(source).valid, true); source.riskBids.navigator.riskBidId = "missing"; assert.equal(validateVoyageEncounterRiskBids(source).errors.at(-1).code, "risk-bid-not-available"); assert.deepEqual(source.selections, before.selections); });
test("selects, changes, and clears a bid atomically", () => { const source = state(); const selected = applyVoyageEncounterRiskBidSelection(source, { stationId: "navigator", riskBidId: "close" }); assert.equal(selected.ok, true); assert.deepEqual(selected.nextState.riskBids.navigator, { stationId: "navigator", actionId: "thread", riskBidId: "close" }); assert.equal(selected.events[0].type, "voyage.risk-bid-selected"); const changed = applyVoyageEncounterRiskBidChange(selected.nextState, { stationId: "navigator", riskBidId: "bold" }); assert.equal(changed.ok, true); assert.equal(changed.events[0].previousRiskBidId, "close"); const cleared = applyVoyageEncounterRiskBidClear(changed.nextState, { stationId: "navigator" }); assert.equal(cleared.ok, true); assert.deepEqual(cleared.nextState.riskBids, {}); assert.equal(cleared.events[0].riskBidId, "bold"); assert.equal(source.revision, 3); });
test("rejects invalid request, duplicate bid, missing selection, and locked edits", () => { const source = state(); assert.equal(applyVoyageEncounterRiskBidSelection(source, null).ok, false); const selected = applyVoyageEncounterRiskBidSelection(source, { stationId: "navigator", riskBidId: "close" }); assert.equal(applyVoyageEncounterRiskBidSelection(selected.nextState, { stationId: "navigator", riskBidId: "bold" }).errors[0].code, "risk-bid-already-exists"); const noSelection = state(); delete noSelection.selections.navigator; assert.equal(applyVoyageEncounterRiskBidSelection(noSelection, { stationId: "navigator", riskBidId: "close" }).errors[0].code, "risk-bid-selection-missing"); selected.nextState.phase = VOYAGE_ROUND_PHASES.LOCK_READINESS; assert.equal(applyVoyageEncounterRiskBidClear(selected.nextState, { stationId: "navigator" }).errors[0].code, "risk-bid-requires-crew-planning"); });
test("action edits clear coupled risk bids in their one primary event", () => { const source = state(); source.riskBids.navigator = { stationId: "navigator", actionId: "thread", riskBidId: "close" }; const changed = applyVoyageEncounterStationActionSelectionChange(source, { stationId: "navigator", actionId: "safe" }); assert.equal(changed.ok, true); assert.deepEqual(changed.nextState.riskBids, {}); assert.equal(changed.events[0].clearedRiskBidId, "close"); const cleared = applyVoyageEncounterStationActionSelectionClear(source, { stationId: "navigator" }); assert.equal(cleared.ok, true); assert.equal(cleared.events[0].clearedRiskBidId, "close"); });
test("imports without Foundry globals and rejects malformed authored options", () => { const source = state(); source.availableStations[0].actions[0].riskBidOptions = [{ riskBidId: "close" }, { riskBidId: "close" }]; source.riskBids.navigator = { stationId: "navigator", actionId: "thread", riskBidId: "close" }; assert.equal(validateVoyageEncounterRiskBids(source).valid, false); assert.equal(typeof validateVoyageEncounterRiskBids, "function"); });
