import { VOYAGE_ACTION_EXECUTION_MODES as MODES, VOYAGE_ENCOUNTER_LIFECYCLE_STATES as LIFE, VOYAGE_ROUND_PHASES as PHASES } from "./constants.js";
import { clonePlainData, isPlainObject } from "./defaults.js";
import { validateVoyageEncounterState } from "./validation.js";
import { deduplicateVoyageResolutionIssues } from "./resolution-order.js";
import { prepareVoyageEncounterActionExecutionRequests } from "./resolution-execution-requests.js";
const REQUIRED = ["pendingCheckId", "preparedRevision", "stageId", "roundNumber", "sequence", "stationId", "actionId", "resolutionPriority", "riskBidId", "target", "mode", "source", "statisticOptions", "dcSource", "secrecy", "metadata", "status", "result"];
const UNSAFE = new Set(["__proto__", "constructor", "prototype"]);
const issue = (errors, code, path, message) => errors.push({ code, path, message, severity: "error" });
const indices = (a) => Array.isArray(a) ? Array.from({ length: a.length }, (_, i) => i).filter((i) => Object.hasOwn(a, i)) : [];
const equal = (a, b) => { if (Object.is(a, b)) return true; if (Array.isArray(a) && Array.isArray(b)) return a.length === b.length && indices(a).length === indices(b).length && indices(a).every((i) => Object.hasOwn(b, i) && equal(a[i], b[i])); if (!isPlainObject(a) || !isPlainObject(b)) return false; const ak = Object.keys(a), bk = Object.keys(b); return ak.length === bk.length && ak.every((k) => Object.hasOwn(b, k) && equal(a[k], b[k])); };
const validId = (v) => typeof v === "string" && v.length > 0 && !UNSAFE.has(v);
export function validateVoyageEncounterPendingChecks(state) {
  const structural = validateVoyageEncounterState(state); const errors = [...structural.errors], warnings = [...structural.warnings]; if (!structural.valid) return { valid: false, errors: deduplicateVoyageResolutionIssues(errors), warnings: deduplicateVoyageResolutionIssues(warnings) };
  const report = prepareVoyageEncounterActionExecutionRequests(state); warnings.push(...report.warnings); if (!Array.isArray(state.pendingChecks)) issue(errors, "invalid-pending-checks", "pendingChecks", "pendingChecks must be an array.");
  const expected = new Map(report.executionRequests.filter((r) => r.mode === MODES.CHECK).map((r) => [r.sequence, r])); const ids = new Set(), sequences = new Set(); let previous = -1;
  for (const i of indices(state.pendingChecks)) { const record = state.pendingChecks[i], path = `pendingChecks[${i}]`; if (!isPlainObject(record)) { issue(errors, "invalid-pending-check", path, "Pending check must be a plain object."); continue; } for (const key of REQUIRED) if (!Object.hasOwn(record, key)) issue(errors, "missing-pending-check-field", `${path}.${key}`, `Pending check requires ${key}.`); if (!validId(record.pendingCheckId)) issue(errors, "invalid-pending-check-id", `${path}.pendingCheckId`, "Pending check ID must be a safe non-empty exact string."); else if (ids.has(record.pendingCheckId)) issue(errors, "duplicate-pending-check-id", `${path}.pendingCheckId`, "Pending check IDs must be unique."); else ids.add(record.pendingCheckId); if (!Number.isSafeInteger(record.sequence) || record.sequence < 0) issue(errors, "invalid-pending-check-sequence", `${path}.sequence`, "Pending check sequence must be a non-negative safe integer."); else { if (sequences.has(record.sequence)) issue(errors, "duplicate-pending-check-sequence", `${path}.sequence`, "Pending check sequences must be unique."); sequences.add(record.sequence); if (record.sequence < previous) issue(errors, "pending-check-order", `${path}.sequence`, "Pending checks must be in ascending execution sequence."); previous = record.sequence; }
    if (!Number.isSafeInteger(record.preparedRevision) || record.preparedRevision < 0 || record.preparedRevision > state.revision) issue(errors, "invalid-pending-check-prepared-revision", `${path}.preparedRevision`, "preparedRevision must not exceed the encounter revision.");
    if (record.stageId !== state.currentStage?.stageId) issue(errors, "pending-check-stage-mismatch", `${path}.stageId`, "Pending check stage must match current stage."); if (record.roundNumber !== state.roundNumber) issue(errors, "pending-check-round-mismatch", `${path}.roundNumber`, "Pending check round must match current round."); if (record.mode !== MODES.CHECK) issue(errors, "invalid-pending-check-mode", `${path}.mode`, "Pending check mode must be check."); if (record.status !== "pending") issue(errors, "invalid-pending-check-status", `${path}.status`, "Pending check status must be pending."); if (record.result !== null) issue(errors, "invalid-pending-check-result", `${path}.result`, "Pending check result must be null.");
    const request = expected.get(record.sequence); if (!request) issue(errors, "unexpected-pending-check", path, "Pending check does not correspond to a selected check action."); else for (const key of ["stationId", "actionId", "resolutionPriority", "riskBidId", "target", "source", "statisticOptions", "dcSource", "secrecy", "metadata"]) if (!equal(record[key], request[key])) issue(errors, "pending-check-request-mismatch", `${path}.${key}`, `Pending check ${key} must match its execution request.`);
  }
  // An empty collection is the valid, not-yet-prepared Resolution state. Once
  // preparation has begun, it must be complete so reload recovery is unambiguous.
  if (indices(state.pendingChecks).length > 0) for (const sequence of expected.keys()) if (!sequences.has(sequence)) issue(errors, "missing-pending-check", "pendingChecks", `Selected check action sequence ${sequence} has no pending check.`);
  const final = deduplicateVoyageResolutionIssues(errors); return { valid: final.length === 0, errors: final, warnings: deduplicateVoyageResolutionIssues(warnings) };
}
const fail = (errors, warnings = []) => ({ ok: false, nextState: null, events: [], errors: deduplicateVoyageResolutionIssues(errors), warnings: deduplicateVoyageResolutionIssues(warnings) });
export function applyVoyageEncounterPendingCheckPreparation(state, preparationRequest) {
  const structural = validateVoyageEncounterState(state); if (!structural.valid) return fail(structural.errors, structural.warnings); const existing = validateVoyageEncounterPendingChecks(state); const warnings = [...structural.warnings, ...existing.warnings]; if (!existing.valid) return fail(existing.errors, warnings);
  if (state.lifecycleState !== LIFE.ACTIVE) return fail([{ code: "pending-check-preparation-requires-active", path: "lifecycleState", message: "Preparing pending checks requires an Active encounter.", severity: "error" }], warnings); if (state.phase !== PHASES.RESOLUTION) return fail([{ code: "pending-check-preparation-requires-resolution", path: "phase", message: "Preparing pending checks requires Resolution phase.", severity: "error" }], warnings);
  const report = prepareVoyageEncounterActionExecutionRequests(state); warnings.push(...report.warnings); if (!report.readyForExecution) return fail(report.errors, warnings); if (!report.checkCount) return fail([{ code: "pending-check-preparation-not-required", path: "pendingChecks", message: "This Resolution plan has no check actions.", severity: "error" }], warnings); if (!report.pendingChecksEmpty) return fail([{ code: "pending-checks-not-empty", path: "pendingChecks", message: "Pending checks must be empty before preparation.", severity: "error" }], warnings);
  const errors = []; if (!isPlainObject(preparationRequest)) issue(errors, "invalid-pending-check-preparation-request", "preparationRequest", "Preparation request must be a plain object."); if (!isPlainObject(preparationRequest) || !Object.hasOwn(preparationRequest, "pendingCheckIds") || !Array.isArray(preparationRequest.pendingCheckIds)) issue(errors, "invalid-pending-check-id-mappings", "preparationRequest.pendingCheckIds", "Preparation requires an own pendingCheckIds array."); const mappings = new Map(), ids = new Set();
  if (Array.isArray(preparationRequest?.pendingCheckIds)) for (const i of indices(preparationRequest.pendingCheckIds)) { const entry = preparationRequest.pendingCheckIds[i], path = `preparationRequest.pendingCheckIds[${i}]`; if (!isPlainObject(entry)) { issue(errors, "invalid-pending-check-id-mapping", path, "Pending check ID mapping must be a plain object."); continue; } if (!Object.hasOwn(entry, "sequence") || !Number.isSafeInteger(entry.sequence) || entry.sequence < 0) issue(errors, "invalid-pending-check-mapping-sequence", `${path}.sequence`, "Mapping sequence must be a non-negative safe integer."); if (!Object.hasOwn(entry, "pendingCheckId") || !validId(entry.pendingCheckId)) issue(errors, "invalid-pending-check-mapping-id", `${path}.pendingCheckId`, "Mapping pendingCheckId must be safe and non-empty."); if (Number.isSafeInteger(entry.sequence) && entry.sequence >= 0) { if (mappings.has(entry.sequence)) issue(errors, "duplicate-pending-check-mapping-sequence", `${path}.sequence`, "Mapping sequences must be unique."); mappings.set(entry.sequence, entry.pendingCheckId); } if (validId(entry.pendingCheckId)) { if (ids.has(entry.pendingCheckId)) issue(errors, "duplicate-pending-check-mapping-id", `${path}.pendingCheckId`, "Mapping IDs must be unique."); ids.add(entry.pendingCheckId); } }
  const checks = report.executionRequests.filter((r) => r.mode === MODES.CHECK); for (const r of checks) if (!mappings.has(r.sequence)) issue(errors, "missing-pending-check-mapping", "preparationRequest.pendingCheckIds", `Check sequence ${r.sequence} requires an ID mapping.`); for (const sequence of mappings.keys()) if (!checks.some((r) => r.sequence === sequence)) issue(errors, "unexpected-pending-check-mapping", "preparationRequest.pendingCheckIds", "Mapping does not identify a check-producing sequence."); if (errors.length) return fail(errors, warnings);
  let candidate; try { candidate = clonePlainData(state); candidate.revision = state.revision + 1; candidate.pendingChecks = checks.map((r) => ({ pendingCheckId: mappings.get(r.sequence), preparedRevision: candidate.revision, stageId: candidate.currentStage.stageId, roundNumber: candidate.roundNumber, ...clonePlainData(r), status: "pending", result: null })); } catch { return fail([{ code: "pending-check-candidate-construction-failed", path: "encounterState", message: "Pending check preparation could not clone encounter state.", severity: "error" }], warnings); }
  const final = validateVoyageEncounterState(candidate), pending = validateVoyageEncounterPendingChecks(candidate); warnings.push(...final.warnings, ...pending.warnings); if (!final.valid || !pending.valid) return fail([...final.errors, ...pending.errors], warnings);
  const preparedChecks = candidate.pendingChecks.map(({ pendingCheckId, sequence, stationId, actionId }) => ({ pendingCheckId, sequence, stationId, actionId })); return { ok: true, nextState: candidate, events: [{ type: "voyage.pending-checks-prepared", encounterId: candidate.encounterId, lifecycleState: candidate.lifecycleState, roundNumber: candidate.roundNumber, phase: candidate.phase, actionCount: report.actionCount, checkCount: report.checkCount, noRollActionCount: report.noRollActionCount, preparedChecks: clonePlainData(preparedChecks), previousRevision: state.revision, revision: candidate.revision }], errors: [], warnings: deduplicateVoyageResolutionIssues(warnings) };
}
