import { prepareTravelV2RiskBidBenefitRewardApply, TRAVEL_V2_RISK_BID_BENEFIT_REWARD_APPLY_VERSION } from "./travel-v2-risk-bid-benefit-reward-apply.js";

function assertSmoke(condition, message) { if (!condition) throw new Error(`Travel v2 risk bid benefit reward apply smoke check failed: ${message}`); }
function assertEqual(actual, expected, message) { if (actual !== expected) throw new Error(`Travel v2 risk bid benefit reward apply smoke check failed: ${message}. Expected ${expected}, got ${actual}.`); }
function reviewedRecord(overrides = {}) { return { queueKey: overrides.queueKey ?? "queue:positive:1", source: "riskBidResult", status: "reviewed", selected: true, payloadType: overrides.payloadType ?? "benefitReview", candidateType: overrides.candidateType ?? "benefit", severity: overrides.severity ?? "moderate", tier: overrides.tier ?? 8, resultBand: overrides.resultBand ?? "success", dangerLevel: overrides.dangerLevel ?? "none", stationKey: overrides.stationKey ?? "navigator", stationName: overrides.stationName ?? "Navigator", actionId: overrides.actionId ?? "plot-course", actionName: overrides.actionName ?? "Plot Course", roundIndex: 0, roundNumber: 1, label: overrides.label ?? "Positive risk", text: overrides.text ?? "Hold for later positive resolution." }; }
function sessionWith(records) { return { event: { name: "Risk" }, travelV2RiskBidReviewQueue: { records } }; }
function assertNoForbidden(value, message) { const json = JSON.stringify(value); for (const forbidden of ["gmOnly", "secret", "hiddenHazards", "unrevealedHazard", "futureTriggers", "internalScoring", "debugReport", "auditRecord", "applyPayload", "actorUuid", "targetActorUuid", "userId", "userName", "updateData", "actor.update", "ChatMessage", "JournalEntry", "socket", "Compendium.", "Actor.", "Item."]) assertSmoke(!json.includes(forbidden), `${message} excludes ${forbidden}`); }

export default async function runTravelV2RiskBidBenefitRewardApplySmokeChecks() {
  assertEqual(TRAVEL_V2_RISK_BID_BENEFIT_REWARD_APPLY_VERSION, 1, "helper export exists");
  assertEqual(typeof prepareTravelV2RiskBidBenefitRewardApply, "function", "prepare helper export exists");
  assertSmoke(prepareTravelV2RiskBidBenefitRewardApply(sessionWith([reviewedRecord()]), { canReview: false }).blockedReasons.includes("travel-v2-review-permission-required"), "non-GM blocks");
  assertSmoke(prepareTravelV2RiskBidBenefitRewardApply({}, { canReview: true }).blockedReasons.includes("risk-bid-review-queue-not-found"), "missing queue blocks");
  assertSmoke(prepareTravelV2RiskBidBenefitRewardApply(sessionWith([]), { canReview: true }).blockedReasons.includes("missing-armed-risk-bid-review-apply-gate-records"), "no armed gate records blocks");
  assertSmoke(prepareTravelV2RiskBidBenefitRewardApply(sessionWith([reviewedRecord({ payloadType: "pressureReview", candidateType: "pressureCandidate" })]), { canReview: true }).blockedReasons.includes("missing-risk-bid-benefit-reward-gate-records"), "no benefit/reward gate records blocks");
  for (const applyMode of ["freeform", "secret", "applyPayload"]) { const invalid = prepareTravelV2RiskBidBenefitRewardApply(sessionWith([reviewedRecord()]), { canReview: true, applyMode }); assertSmoke(invalid.blockedReasons.includes("invalid-risk-bid-benefit-reward-apply-mode"), "invalid apply mode blocks"); assertNoForbidden(invalid, "invalid apply mode output"); }

  const baseSession = sessionWith([reviewedRecord()]); const snapshot = JSON.stringify(baseSession);
  const preview = prepareTravelV2RiskBidBenefitRewardApply(baseSession, { canReview: true, applyMode: "preview" });
  assertEqual(preview.positiveRecords.length, 1, "preview mode creates positive records"); assertEqual(preview.sessionPatch, null, "preview mode creates no sessionPatch"); assertEqual(preview.staged, false, "preview staged false"); assertEqual(preview.committed, false, "preview committed false"); assertEqual(preview.applied, false, "preview applied false");
  assertEqual(preview.positiveRecords[0].benefitDelta, 1, "benefit maps benefitDelta"); assertEqual(preview.positiveRecords[0].positiveKind, "benefit", "benefit maps kind"); assertEqual(preview.positiveRecords[0].positiveKey, `risk-bid-benefit-reward-apply:${preview.positiveRecords[0].gateKey}`, "positive key is deterministic"); assertEqual(preview.positiveRecords[0].positiveOnly, true, "positiveOnly true"); assertEqual(preview.positiveRecords[0].previewOnly, true, "previewOnly preserved"); assertEqual(preview.positiveRecords[0].intentOnly, true, "intentOnly preserved"); assertEqual(preview.positiveRecords[0].gateOnly, true, "gateOnly preserved"); assertEqual(preview.positiveRecords[0].armed, true, "armed preserved");
  const expectedKeys = ["positiveVersion", "positiveKey", "gateKey", "intentKey", "queueKey", "status", "payloadType", "candidateType", "severity", "tier", "resultBand", "dangerLevel", "stationKey", "stationName", "actionId", "actionName", "roundIndex", "roundNumber", "label", "text", "resolutionType", "resolutionFamily", "positiveKind", "positiveDelta", "benefitDelta", "momentumDelta", "rewardDelta", "positiveSeverity", "previewOnly", "intentOnly", "gateOnly", "positiveOnly", "armed", "applied"];
  assertEqual(Object.keys(preview.positiveRecords[0]).sort().join(","), expectedKeys.slice().sort().join(","), "positive record has exact safe shape"); assertEqual(JSON.stringify(baseSession), snapshot, "input session is not mutated");

  const stage = prepareTravelV2RiskBidBenefitRewardApply(baseSession, { canReview: true, applyMode: "stage", now: "2026-07-13T00:00:00.000Z" });
  assertSmoke(stage.sessionPatch?.travelV2RiskBidBenefitRewardApply, "stage mode creates safe sessionPatch"); assertEqual(stage.staged, true, "stage staged true"); assertEqual(stage.committed, false, "stage committed false"); assertEqual(stage.applied, false, "stage applied false");

  const mixedSession = sessionWith([reviewedRecord({ queueKey: "benefit", payloadType: "benefitReview", candidateType: "benefit", severity: "minor" }), reviewedRecord({ queueKey: "progress", payloadType: "progressReview", candidateType: "progress", dangerLevel: "low" }), reviewedRecord({ queueKey: "momentum", payloadType: "momentumReview", candidateType: "momentumCandidate", severity: "moderate" }), reviewedRecord({ queueKey: "reward", payloadType: "rewardReview", candidateType: "rewardImprovement", dangerLevel: "high" }), reviewedRecord({ queueKey: "pressure", payloadType: "pressureReview", candidateType: "pressureCandidate" }), reviewedRecord({ queueKey: "hazard", payloadType: "hazardProgressReview", candidateType: "hazardProgressCandidate" }), reviewedRecord({ queueKey: "consequence", payloadType: "consequenceReview", candidateType: "consequenceCandidate" }), reviewedRecord({ queueKey: "scar", payloadType: "shipScarReview", candidateType: "shipScarCandidate" })]);
  const mixed = prepareTravelV2RiskBidBenefitRewardApply(mixedSession, { canReview: true, applyMode: "commit", now: "2026-07-13T00:00:00.000Z" });
  assertEqual(mixed.positiveRecords.length, 4, "pressure/hazard/consequence/scar gate records are ignored"); assertEqual(mixed.positiveDeltaTotal, 4, "mixed positive records total correctly"); assertEqual(mixed.benefitDeltaTotal, 2, "mixed benefit total"); assertEqual(mixed.momentumDeltaTotal, 1, "mixed momentum total"); assertEqual(mixed.rewardDeltaTotal, 1, "mixed reward total");
  assertEqual(mixed.positiveRecords.find((r) => r.resolutionType === "progress").positiveKind, "progress", "progress maps positiveKind"); assertEqual(mixed.positiveRecords.find((r) => r.resolutionType === "progress").benefitDelta, 1, "progress maps benefitDelta"); assertEqual(mixed.positiveRecords.find((r) => r.resolutionType === "momentum").momentumDelta, 1, "momentum maps momentumDelta"); assertEqual(mixed.positiveRecords.find((r) => r.resolutionType === "reward").rewardDelta, 1, "reward maps rewardDelta");
  assertEqual(mixed.byResolutionFamily.benefit, 2, "counts benefit family"); assertEqual(mixed.byResolutionFamily.momentum, 1, "counts momentum family"); assertEqual(mixed.byResolutionFamily.reward, 1, "counts reward family"); assertEqual(mixed.byResolutionType.benefit, 1, "counts benefit type"); assertEqual(mixed.byResolutionType.progress, 1, "counts progress type"); assertEqual(mixed.byPositiveKind.benefit, 1, "counts benefit kind"); assertEqual(mixed.byPositiveKind.progress, 1, "counts progress kind"); assertSmoke(mixed.byDangerLevel.none >= 1 && mixed.byDangerLevel.low === 1 && mixed.byDangerLevel.high === 1, "counts by danger"); assertSmoke(mixed.bySeverity.minor === 1 && mixed.bySeverity.moderate >= 1, "counts by severity");
  assertSmoke(mixed.sessionPatch?.travelV2RiskBidBenefitRewardApply, "commit mode creates safe sessionPatch"); assertSmoke(mixed.session?.travelV2RiskBidBenefitRewardApply, "commit mode creates cloned session"); assertSmoke(mixed.session !== mixedSession, "commit output session is a clone"); assertEqual(mixed.staged, true, "commit staged true"); assertEqual(mixed.committed, true, "commit committed true"); assertEqual(mixed.applied, true, "commit applied true"); assertSmoke(mixed.positiveRecords.every((record) => record.applied === true), "commit positive records marked applied session-locally"); assertEqual(JSON.stringify(mixedSession), JSON.stringify(sessionWith(mixedSession.travelV2RiskBidReviewQueue.records)), "commit does not mutate input session");
  assertNoForbidden(preview, "preview output"); assertNoForbidden(stage, "stage output"); assertNoForbidden(mixed, "commit output"); assertSmoke(!JSON.stringify(mixed).includes("world"), "no world mutation side effects occur");
  return { checked: ["risk-bid-benefit-reward-apply"] };
}
