import { prepareTravelV2RiskBidScarApply, TRAVEL_V2_RISK_BID_SCAR_APPLY_VERSION } from "./travel-v2-risk-bid-scar-apply.js";

function assertSmoke(condition, message) { if (!condition) throw new Error(`Travel v2 risk bid scar apply smoke check failed: ${message}`); }
function assertEqual(actual, expected, message) { if (actual !== expected) throw new Error(`Travel v2 risk bid scar apply smoke check failed: ${message}. Expected ${expected}, got ${actual}.`); }
function reviewedRecord(overrides = {}) { return { queueKey: overrides.queueKey ?? "queue:scar:1", source: "riskBidResult", status: "reviewed", selected: true, payloadType: overrides.payloadType ?? "shipScarReview", candidateType: overrides.candidateType ?? "shipScarCandidate", severity: overrides.severity ?? "moderate", tier: overrides.tier ?? 8, resultBand: overrides.resultBand ?? "criticalFailure", dangerLevel: overrides.dangerLevel ?? "high", stationKey: overrides.stationKey ?? "navigator", stationName: overrides.stationName ?? "Navigator", actionId: overrides.actionId ?? "plot-course", actionName: overrides.actionName ?? "Plot Course", roundIndex: 0, roundNumber: 1, label: overrides.label ?? "Scar risk", text: overrides.text ?? "Hold for later scar resolution." }; }
function sessionWith(records) { return { event: { name: "Risk" }, travelV2RiskBidReviewQueue: { records } }; }
function assertNoForbidden(value, message) { const json = JSON.stringify(value); for (const forbidden of ["gmOnly", "secret", "hiddenHazards", "unrevealedHazard", "futureTriggers", "internalScoring", "debugReport", "auditRecord", "applyPayload", "actorUuid", "targetActorUuid", "userId", "userName", "updateData", "actor.update", "ChatMessage", "JournalEntry", "socket", "Compendium.", "Actor.", "Item."]) assertSmoke(!json.includes(forbidden), `${message} excludes ${forbidden}`); }

export default async function runTravelV2RiskBidScarApplySmokeChecks() {
  assertEqual(TRAVEL_V2_RISK_BID_SCAR_APPLY_VERSION, 1, "helper export exists");
  assertEqual(typeof prepareTravelV2RiskBidScarApply, "function", "prepare helper export exists");
  assertSmoke(prepareTravelV2RiskBidScarApply(sessionWith([reviewedRecord()]), { canReview: false }).blockedReasons.includes("travel-v2-review-permission-required"), "non-GM blocks");
  assertSmoke(prepareTravelV2RiskBidScarApply({}, { canReview: true }).blockedReasons.includes("risk-bid-review-queue-not-found"), "missing queue blocks");
  assertSmoke(prepareTravelV2RiskBidScarApply(sessionWith([]), { canReview: true }).blockedReasons.includes("missing-armed-risk-bid-review-apply-gate-records"), "no armed gate records blocks");
  assertSmoke(prepareTravelV2RiskBidScarApply(sessionWith([reviewedRecord({ payloadType: "pressureReview", candidateType: "pressureCandidate" })]), { canReview: true }).blockedReasons.includes("missing-risk-bid-scar-gate-records"), "no scar gate records blocks");
  for (const applyMode of ["freeform", "secret", "applyPayload"]) { const invalid = prepareTravelV2RiskBidScarApply(sessionWith([reviewedRecord()]), { canReview: true, applyMode }); assertSmoke(invalid.blockedReasons.includes("invalid-risk-bid-scar-apply-mode"), "invalid apply mode blocks"); assertNoForbidden(invalid, "invalid apply mode output"); }

  const baseSession = sessionWith([reviewedRecord()]); const snapshot = JSON.stringify(baseSession);
  const preview = prepareTravelV2RiskBidScarApply(baseSession, { canReview: true, applyMode: "preview" });
  assertEqual(preview.scarRecords.length, 1, "preview mode creates scar records"); assertEqual(preview.sessionPatch, null, "preview mode creates no sessionPatch"); assertEqual(preview.staged, false, "preview staged false"); assertEqual(preview.committed, false, "preview committed false"); assertEqual(preview.applied, false, "preview applied false");
  assertEqual(preview.scarRecords[0].scarDelta, 1, "shipScar maps scarDelta"); assertEqual(preview.scarRecords[0].scarKind, "shipScar", "shipScar maps scarKind"); assertEqual(preview.scarRecords[0].scarKey, `risk-bid-scar-apply:${preview.scarRecords[0].gateKey}`, "scar key is deterministic"); assertEqual(preview.scarRecords[0].scarOnly, true, "scarOnly true"); assertEqual(preview.scarRecords[0].previewOnly, true, "previewOnly preserved"); assertEqual(preview.scarRecords[0].intentOnly, true, "intentOnly preserved"); assertEqual(preview.scarRecords[0].gateOnly, true, "gateOnly preserved"); assertEqual(preview.scarRecords[0].armed, true, "armed preserved");
  const expectedKeys = ["scarVersion", "scarKey", "gateKey", "intentKey", "queueKey", "status", "payloadType", "candidateType", "severity", "tier", "resultBand", "dangerLevel", "stationKey", "stationName", "actionId", "actionName", "roundIndex", "roundNumber", "label", "text", "resolutionType", "resolutionFamily", "scarDelta", "scarKind", "scarSeverity", "previewOnly", "intentOnly", "gateOnly", "scarOnly", "armed", "applied"];
  assertEqual(Object.keys(preview.scarRecords[0]).sort().join(","), expectedKeys.slice().sort().join(","), "scar record has exact safe shape"); assertEqual(JSON.stringify(baseSession), snapshot, "input session is not mutated");

  const stage = prepareTravelV2RiskBidScarApply(baseSession, { canReview: true, applyMode: "stage", now: "2026-07-13T00:00:00.000Z" });
  assertSmoke(stage.sessionPatch?.travelV2RiskBidScarApply, "stage mode creates safe sessionPatch"); assertEqual(stage.staged, true, "stage staged true"); assertEqual(stage.committed, false, "stage committed false"); assertEqual(stage.applied, false, "stage applied false");

  const mixedSession = sessionWith([reviewedRecord({ queueKey: "scar-1", severity: "minor" }), reviewedRecord({ queueKey: "scar-2", dangerLevel: "low" }), reviewedRecord({ queueKey: "pressure", payloadType: "pressureReview", candidateType: "pressureCandidate" }), reviewedRecord({ queueKey: "hazard", payloadType: "hazardProgressReview", candidateType: "hazardProgressCandidate" }), reviewedRecord({ queueKey: "consequence", payloadType: "consequenceReview", candidateType: "consequenceCandidate" }), reviewedRecord({ queueKey: "benefit", payloadType: "benefitReview", candidateType: "benefit" }), reviewedRecord({ queueKey: "momentum", payloadType: "momentumReview", candidateType: "momentumCandidate" }), reviewedRecord({ queueKey: "reward", payloadType: "rewardReview", candidateType: "rewardImprovement" })]);
  const mixed = prepareTravelV2RiskBidScarApply(mixedSession, { canReview: true, applyMode: "commit", now: "2026-07-13T00:00:00.000Z" });
  assertEqual(mixed.scarRecords.length, 2, "pressure/hazard/consequence/benefit/Momentum/reward gate records are ignored"); assertEqual(mixed.scarDeltaTotal, 2, "mixed records total correctly");
  assertEqual(mixed.byResolutionType.shipScar, 2, "counts by resolution type"); assertEqual(mixed.byScarKind.shipScar, 2, "counts by scar kind"); assertSmoke(mixed.byDangerLevel.high >= 1 && mixed.byDangerLevel.low === 1, "counts by danger"); assertSmoke(mixed.bySeverity.minor === 1 && mixed.bySeverity.moderate >= 1, "counts by severity");
  assertSmoke(mixed.sessionPatch?.travelV2RiskBidScarApply, "commit mode creates safe sessionPatch"); assertSmoke(mixed.session?.travelV2RiskBidScarApply, "commit mode creates cloned session"); assertSmoke(mixed.session !== mixedSession, "commit output session is a clone"); assertEqual(mixed.staged, true, "commit staged true"); assertEqual(mixed.committed, true, "commit committed true"); assertEqual(mixed.applied, true, "commit applied true"); assertSmoke(mixed.scarRecords.every((record) => record.applied === true), "commit scar records marked applied session-locally"); assertEqual(JSON.stringify(mixedSession), JSON.stringify(sessionWith(mixedSession.travelV2RiskBidReviewQueue.records)), "commit does not mutate input session");
  assertNoForbidden(preview, "preview output"); assertNoForbidden(stage, "stage output"); assertNoForbidden(mixed, "commit output"); assertSmoke(!JSON.stringify(mixed).includes("world"), "no actor/item/chat/journal/socket/world mutation side effects occur");
  return { checked: ["risk-bid-scar-apply"] };
}
