import { VOYAGE_EVENT_BID_BANDS, VOYAGE_EVENT_MECHANICS_VERSION, VOYAGE_EVENT_NARRATIVE_COMPONENT_TYPES, VOYAGE_EVENT_PACKAGE_SCHEMA_VERSION, VOYAGE_EVENT_ROUND_RESULTS, VOYAGE_EVENT_STATION_KEYS } from "./constants.js";

const plainObject = (value) => value !== null && typeof value === "object" && !Array.isArray(value) && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null);
const nonEmpty = (value) => typeof value === "string" && value.trim().length > 0;
const add = (issues, severity, code, path, message, referenceId) => issues.push({ severity, code, path, message, ...(referenceId ? { referenceId } : {}) });
const bidBands = Object.values(VOYAGE_EVENT_BID_BANDS);

/** Validates declarative package data without mutating, executing, or requiring Foundry globals. */
export function validateVoyageEventPackage(packageData, { catalogs } = {}) {
  const errors = [], warnings = [], ids = { rounds: new Set(), actions: new Set(), components: new Set() };
  inspectSafeData(packageData, "package", errors, new Set());
  if (!plainObject(packageData)) { add(errors, "error", "package.invalid", "package", "Package must be a plain object."); return { valid: false, errors, warnings }; }
  for (const key of ["packageVersion", "packageId", "title", "category"]) if (!nonEmpty(packageData[key])) add(errors, "error", "package.required", `package.${key}`, "Value must be a non-empty string.");
  if (packageData.schemaVersion !== VOYAGE_EVENT_PACKAGE_SCHEMA_VERSION) add(errors, "error", "package.schemaVersion.unsupported", "package.schemaVersion", "Package schema version is unsupported.");
  if (String(packageData.mechanicsVersion) !== String(VOYAGE_EVENT_MECHANICS_VERSION)) add(errors, "error", "package.mechanicsVersion.unsupported", "package.mechanicsVersion", "Package mechanics version is unsupported.");
  if (!Array.isArray(packageData.tags) || !packageData.tags.every((tag) => typeof tag === "string")) add(errors, "error", "package.tags.invalid", "package.tags", "Tags must be an array of strings.");
  if (packageData.artworkRoles !== undefined && !plainObject(packageData.artworkRoles)) add(errors, "error", "package.artworkRoles.invalid", "package.artworkRoles", "Artwork roles must be a plain object.");
  for (const [key, value] of Object.entries(packageData.artworkRoles ?? {})) if (typeof value !== "string") add(errors, "error", "package.artworkRole.invalid", `package.artworkRoles.${key}`, "Artwork role values must be strings.");
  for (const key of ["minimumRounds", "maximumRounds"]) if (!Number.isInteger(packageData[key]) || packageData[key] < 3 || packageData[key] > 11) add(errors, "error", "package.roundLimit.invalid", `package.${key}`, "Round limits must be integers from 3 through 11.");
  if (packageData.minimumRounds > packageData.maximumRounds) add(errors, "error", "package.roundLimits.order", "package.minimumRounds", "Minimum rounds cannot exceed maximum rounds.");
  const rounds = Array.isArray(packageData.rounds) ? packageData.rounds : [];
  if (!Array.isArray(packageData.rounds)) add(errors, "error", "package.rounds.invalid", "package.rounds", "Rounds must be an array.");
  if (rounds.length < packageData.minimumRounds || rounds.length > packageData.maximumRounds) add(errors, "error", "package.roundCount.invalid", "package.rounds", "Round count is outside declared limits.");
  rounds.forEach((round, index) => validateRound(round, index, ids, errors, warnings, catalogs));
  validateComponents(packageData.narrativeComponents, ids, errors, warnings, catalogs);
  validateLocalReferences(rounds, packageData.narrativeComponents, ids, errors);
  return { valid: errors.length === 0, errors, warnings };
}

function validateRound(round, index, ids, errors, warnings, catalogs) {
  const path = `rounds[${index}]`; if (!plainObject(round)) return add(errors, "error", "round.invalid", path, "Round must be a plain object.");
  unique(round.roundId, ids.rounds, errors, `${path}.roundId`, "round");
  if (!Number.isInteger(round.roundNumber) || round.roundNumber !== index + 1) add(errors, "error", "round.number.invalid", `${path}.roundNumber`, "Round numbers must be contiguous and begin at 1.");
  for (const key of ["title", "immediateGoal"]) if (!nonEmpty(round[key])) add(errors, "error", "round.required", `${path}.${key}`, "Value must be a non-empty string.");
  const actions = plainObject(round.stationActions) ? round.stationActions : {};
  if (!plainObject(round.stationActions)) add(errors, "error", "round.stationActions.invalid", `${path}.stationActions`, "Station actions must be a plain object.");
  for (const stationKey of VOYAGE_EVENT_STATION_KEYS) { const bucket = actions[stationKey]; if (!Array.isArray(bucket) || bucket.length < 1 || bucket.length > 2) add(errors, "error", "round.stationActions.bucket.invalid", `${path}.stationActions.${stationKey}`, "Each active station requires one or two actions."); else bucket.forEach((action, actionIndex) => validateAction(action, stationKey, `${path}.stationActions.${stationKey}[${actionIndex}]`, ids, errors, warnings, catalogs)); }
  Object.keys(actions).filter((key) => !VOYAGE_EVENT_STATION_KEYS.includes(key)).forEach((key) => add(errors, "error", "round.stationActions.unknown", `${path}.stationActions.${key}`, "Unknown station bucket is not allowed."));
  references(round.visibleDangerIds, "dangers", `${path}.visibleDangerIds`, errors, warnings, catalogs); references(round.hiddenDangerIds, "dangers", `${path}.hiddenDangerIds`, errors, warnings, catalogs); references(round.failureConsequenceIds, "consequences", `${path}.failureConsequenceIds`, errors, warnings, catalogs); references(round.criticalFailureConsequenceIds, "consequences", `${path}.criticalFailureConsequenceIds`, errors, warnings, catalogs); externalReference(round.preparedCriticalSuccessAdvantageId, "preparedAdvantages", `${path}.preparedCriticalSuccessAdvantageId`, errors, warnings, catalogs);
}

function validateAction(action, stationKey, path, ids, errors, warnings, catalogs) {
  if (!plainObject(action)) return add(errors, "error", "action.invalid", path, "Action must be a plain object.");
  unique(action.actionId, ids.actions, errors, `${path}.actionId`, "action"); if (action.stationKey !== stationKey) add(errors, "error", "action.stationKey.mismatch", `${path}.stationKey`, "Action station key must match its station bucket.");
  for (const key of ["title", "description"]) if (!nonEmpty(action[key])) add(errors, "error", "action.required", `${path}.${key}`, "Value must be a non-empty string.");
  if (!Array.isArray(action.skills) || action.skills.length !== 3 || new Set(action.skills.map((skill) => skill?.key)).size !== 3 || !action.skills.every((skill) => nonEmpty(skill?.key))) add(errors, "error", "action.skills.invalid", `${path}.skills`, "Actions require exactly three unique non-empty skill keys.");
  if (!Number.isFinite(action.baseDc?.value)) add(errors, "error", "action.baseDc.invalid", `${path}.baseDc.value`, "Base DC value must be finite.");
  const bids = plainObject(action.bids) ? action.bids : {};
  for (const band of bidBands) { const bid = bids[band]; if (!plainObject(bid) || bid.band !== band) { add(errors, "error", "action.bid.invalid", `${path}.bids.${band}`, "Every bid band must exist and match its key."); continue; } const none = band === "none"; if (none ? nonEmpty(bid.rewardId) || nonEmpty(bid.dangerId) : !nonEmpty(bid.rewardId) || !nonEmpty(bid.dangerId)) add(errors, "error", "action.bid.references.invalid", `${path}.bids.${band}`, none ? "No Bid must have empty reward and danger IDs." : "A bid requires reward and danger IDs."); if (!none) { externalReference(bid.rewardId, "rewards", `${path}.bids.${band}.rewardId`, errors, warnings, catalogs); externalReference(bid.dangerId, "dangers", `${path}.bids.${band}.dangerId`, errors, warnings, catalogs); } }
}

function validateComponents(components, ids, errors, warnings, catalogs) { if (!Array.isArray(components)) return add(errors, "error", "narrative.components.invalid", "narrativeComponents", "Narrative components must be an array."); components.forEach((component, index) => { const path = `narrativeComponents[${index}]`; if (!plainObject(component)) return add(errors, "error", "narrative.component.invalid", path, "Narrative component must be a plain object."); unique(component.componentId, ids.components, errors, `${path}.componentId`, "narrative component"); if (!Object.values(VOYAGE_EVENT_NARRATIVE_COMPONENT_TYPES).includes(component.type)) add(errors, "error", "narrative.type.invalid", `${path}.type`, "Narrative component type is unsupported."); if (!nonEmpty(component.text) || !Number.isFinite(component.priority)) add(errors, "error", "narrative.fields.invalid", path, "Narrative text must be non-empty and priority finite."); for (const key of ["requiresFlags", "excludesFlags", "compatibleWith"]) if (!Array.isArray(component[key]) || !component[key].every(nonEmpty)) add(errors, "error", "narrative.array.invalid", `${path}.${key}`, "Narrative metadata must be arrays of non-empty strings."); for (const key of ["sourceStation", "targetStation"]) if (component[key] !== undefined && !VOYAGE_EVENT_STATION_KEYS.includes(component[key])) add(errors, "error", "narrative.station.invalid", `${path}.${key}`, "Narrative station must be active."); if (component.type === "cascadeBridge" && (!VOYAGE_EVENT_STATION_KEYS.includes(component.sourceStation) || !VOYAGE_EVENT_STATION_KEYS.includes(component.targetStation))) add(errors, "error", "narrative.cascadeBridge.invalid", path, "Cascade bridges require active source and target stations."); for (const [key, group] of [["rewardId", "rewards"], ["dangerId", "dangers"], ["hazardId", "hazards"]]) externalReference(component[key], group, `${path}.${key}`, errors, warnings, catalogs, false); }); }

function validateLocalReferences(rounds, components, ids, errors) { const componentIds = ids.components; rounds.forEach((round, roundIndex) => { if (!plainObject(round)) return; const prefix = `rounds[${roundIndex}]`; localReferences(round.openingNarrativeVariants, componentIds, `${prefix}.openingNarrativeVariants`, errors); const conclusions = plainObject(round.shipResultConclusions) ? round.shipResultConclusions : {}; for (const result of Object.values(VOYAGE_EVENT_ROUND_RESULTS)) localReference(conclusions[result], componentIds, `${prefix}.shipResultConclusions.${result}`, errors); localReferences(round.nextRoundTransitions, componentIds, `${prefix}.nextRoundTransitions`, errors); Object.entries(round.stationActions ?? {}).forEach(([stationKey, actions]) => Array.isArray(actions) && actions.forEach((action, actionIndex) => localReferences(action?.narrativeComponentIds, componentIds, `${prefix}.stationActions.${stationKey}[${actionIndex}].narrativeComponentIds`, errors))); }); if (Array.isArray(components)) components.forEach((component, index) => { if (plainObject(component) && component.actionId !== undefined) localReference(component.actionId, ids.actions, `narrativeComponents[${index}].actionId`, errors, "action"); }); }
function localReferences(values, ids, path, errors) { if (!Array.isArray(values)) return add(errors, "error", "reference.local.array.invalid", path, "Package-local references must be an array of stable IDs."); values.forEach((value, index) => localReference(value, ids, `${path}[${index}]`, errors)); }
function localReference(value, ids, path, errors, kind = "narrative component") { if (!nonEmpty(value)) return add(errors, "error", "reference.local.required", path, "Package-local reference must be a non-empty string."); if (!ids.has(value)) add(errors, "error", "reference.local.missing", path, `Referenced ${kind} ID was not found in this package.`, value); }
function unique(value, ids, errors, path, label) { if (!nonEmpty(value)) return add(errors, "error", `${label.replaceAll(" ", ".")}.id.required`, path, `${label} ID must be non-empty.`); if (ids.has(value)) add(errors, "error", `${label.replaceAll(" ", ".")}.id.duplicate`, path, `${label} ID must be unique.`, value); ids.add(value); }
function references(values, group, path, errors, warnings, catalogs) { if (!Array.isArray(values)) return add(errors, "error", "reference.array.invalid", path, "External references must be an array of stable IDs."); values.forEach((value, index) => externalReference(value, group, `${path}[${index}]`, errors, warnings, catalogs)); }
function externalReference(value, group, path, errors, warnings, catalogs, required = true) { if (value === undefined && !required) return; if (!nonEmpty(value)) return required ? add(errors, "error", "reference.id.required", path, "Reference ID must be a non-empty string.") : undefined; if (!catalogs) return add(warnings, "warning", "reference.catalog.unavailable", path, "External catalog lookup was not supplied.", value); const found = typeof catalogs.has === "function" ? catalogs.has(group, value) : catalogs[group]?.[value] !== undefined || (Array.isArray(catalogs[group]) && catalogs[group].some((entry) => entry?.id === value)); if (!found) add(errors, "error", "reference.catalog.missing", path, "Referenced catalog ID was not found.", value); }
function inspectSafeData(value, path, errors, seen) { const type = typeof value; if (["function", "symbol", "bigint", "undefined"].includes(type) || (type === "number" && !Number.isFinite(value))) return add(errors, "error", "data.json.incompatible", path, "Imported data must be JSON-compatible plain data."); if (value && type === "object") { if (seen.has(value)) return add(errors, "error", "data.cyclic", path, "Imported data must not contain cyclic references."); if (!Array.isArray(value) && !plainObject(value)) return add(errors, "error", "data.classInstance", path, "Imported data must not contain class instances."); seen.add(value); Object.entries(value).forEach(([key, entry]) => inspectSafeData(entry, Array.isArray(value) ? `${path}[${key}]` : `${path}.${key}`, errors, seen)); seen.delete(value); } }
