import { ARCFLIGHT } from "./config/constants.js";
import { createArcflightDevTools } from "./dev/dev-tools.js";
import { ArcflightTravelEventBuilder, openTravelEventBuilder, prepareTravelEventBuilderShellState } from "./apps/travel-event-builder.js";
import { ArcflightTravelEventRunner, openTravelEventRunner, prepareSelectedTravelEventLibraryDetails, prepareTravelEventLibraryOptions, prepareTravelEventNarrativeLog } from "./apps/travel-event-runner.js";
import { runFrameworkSmokeTest } from "./dev/framework-smoke-test.js";
import {
  createArcflightItem,
  createArkengine,
  createArkengineMod,
  createCoreArkengine,
  createCoreArkengineMod,
  createCoreCrewAsset,
  createCoreHull,
  createCoreRoom,
  createCoreShipUpgrade,
  createCoreWeapon,
  createCrewAsset,
  createHull,
  createRoom,
  createWeapon,
  createShipUpgrade,
  getArcflightItemDocumentType
} from "./documents/creation.js";
import { CORE_HULL_PLATFORM_KEYS, CORE_HULLS, getCoreHull, getCoreHullPlatformKeys } from "../data/hulls/core-hulls.js";
import { HULL_PATTERN_KEYS, HULL_PATTERNS, getHullPattern, getHullPatternKeys } from "../data/hulls/hull-patterns.js";
import { CORE_ARKENGINE_KEYS, CORE_ARKENGINES, getCoreArkengine, getCoreArkengineKeys } from "../data/arkengines/core-arkengines.js";
import { ARKENGINE_PATTERN_KEYS, ARKENGINE_PATTERNS, getArkenginePattern, getArkenginePatternKeys } from "../data/arkengines/arkengine-patterns.js";
import { CORE_ROOM_KEYS, CORE_ROOMS, getCoreRoom, getCoreRoomKeys } from "../data/rooms/core-rooms.js";
import { CORE_WEAPON_KEYS, CORE_WEAPONS, getCoreWeapon, getCoreWeaponKeys } from "../data/weapons/core-weapons.js";
import { CORE_SHIP_UPGRADE_KEYS, CORE_SHIP_UPGRADES, getCoreShipUpgrade, getCoreShipUpgradeKeys } from "../data/ship-upgrades/core-ship-upgrades.js";
import { CORE_ARKENGINE_MOD_KEYS, CORE_ARKENGINE_MODS, getCoreArkengineMod, getCoreArkengineModKeys } from "../data/arkengine-mods/core-arkengine-mods.js";
import { CORE_STATIONS, STATION_KEYS, getStation, getStationKeys, getStations } from "../data/stations/core-stations.js";
import { CORE_TRAVEL_EVENTS, CORE_TRAVEL_EVENT_KEYS, getCoreTravelEvent, getCoreTravelEventKeys, getCoreTravelEvents, getCoreTravelEventsByCategory } from "../data/travel-events/core-travel-events.js";
import {
  CORE_STATION_ACTION_KEYS,
  CORE_STATION_ACTIONS,
  getCoreStationAction,
  getCoreStationActionKeys,
  getCoreStationActions,
  getCoreStationActionsForStation,
  getStationActionOutcome,
  previewStationActionOutcome
} from "../data/station-actions/core-station-actions.js";
import { CORE_CREW_ASSET_KEYS, CORE_CREW_ASSETS, getCoreCrewAsset, getCoreCrewAssetKeys } from "../data/crew/core-crew-assets.js";
import {
  ARKENGINE_VARIANT_KEYS,
  ARKENGINE_VARIANTS,
  getArkengineVariant,
  getArkengineVariantKeys,
  getArkengineVariants
} from "../data/arkengines/arkengine-variants.js";
import {
  arcflightComponentDefaults,
  getDefaultArcflightComponentData,
  getComponentData,
  getComponentRefitPressure,
  getComponentTierMetadata,
  getComponentType,
  isArcflightItem
} from "./documents/components.js";
import {
  ARCFLIGHT_SHIP_ACTOR_TYPE,
  arcflightShipDefaults,
  calculateDerivedShipStats,
  calculateRefitPressure,
  canSpendShipActionPoints,
  getArcflightShipData,
  getShipActionEconomy,
  getShipTravelResources,
  getTravelStationKeys,
  getShipRefitPressure,
  getShipRefitStatus,
  getShipTierState,
  isTravelStationKey,
  previewShipTravelResourceChange,
  updateShipTravelResources,
  addCrewAsset,
  assignStation,
  clearComponentPatterns,
  clearCrewRoster,
  clearInstalledArkengineMods,
  clearInstalledRooms,
  clearInstalledShipUpgrades,
  clearShipBuild,
  clearStationAssignment,
  clearStationAssignments,
  getDefaultArcflightShipData,
  installArkengine,
  installArkengineMod,
  installArkengineModOnShip,
  installArkengineOnShip,
  installHull,
  installHullOnShip,
  installRoom,
  installRoomOnShip,
  installShipUpgrade,
  installShipUpgradeOnShip,
  installWeapon,
  installWeaponOnShip,
  removeInstalledWeapon,
  recalculateShipStats,
  removeCrewAsset,
  removeInstalledArkengineMod,
  removeInstalledCrewAsset,
  removeInstalledRoom,
  removeInstalledShipUpgrade,
  resetShipActionEconomy,
  spendShipActionPoints,
  updateShipTierState,
  setArkenginePattern,
  setHullPattern
} from "./documents/ships.js";
import { registerArcflightSheets } from "./sheets/registration.js";
import {
  EXAMPLE_SHIP_BUILD_KEYS,
  applyCleanExampleShipBuild,
  applyExampleShipBuild,
  getExampleShipBuild,
  getExampleShipBuildKeys
} from "./helpers/example-ship-builds.js";
import {
  ARCFLIGHT_ITEM_FOLDER_ROOT,
  arcflightComponentFolderNames,
  arcflightItemFolderNames,
  cleanupDuplicateArcflightItems,
  createArcflightItemFolders,
  findDuplicateArcflightItems,
  organizeArcflightItems
} from "./helpers/item-organization.js";
import { findMissingCoreArcflightItems, syncCoreArcflightItems } from "./helpers/core-item-sync.js";
import {
  getTravelFiveStationKeys,
  normalizeTravelDegree,
  getTravelDegreeContribution,
  getTravelRoundOutcome,
  getTravelEventOutcome,
  validateTravelEventDefinition,
  prepareTravelEventSummary,
  prepareTravelRoundSummary,
  getTravelEventStationPrompt
} from "./helpers/travel-events.js";
import {
  TRAVEL_EVENT_TEMPLATE_VERSION,
  createBlankTravelEventTemplate,
  createBlankTravelRoundTemplate,
  createBlankStationPromptTemplate,
  createBlankRollFeedbackTemplate,
  createBlankOutcomeBranchesTemplate,
  createBlankFinalOutcomesTemplate,
  getTravelEventAuthoringGuidelines,
  validateTravelEventAuthoringTemplate
} from "./helpers/travel-event-template.js";
import {
  TRAVEL_EVENT_BUILDER_VERSION,
  createTravelEventDraft,
  normalizeTravelEventDraft,
  validateTravelEventDraft,
  finalizeTravelEventDraft,
  cloneTravelEventToDraft,
  createTravelBuilderResourceEffect,
  createTravelBuilderRound,
  createTravelBuilderStationPrompt,
  createTravelBuilderOutcomeBranch,
  createTravelBuilderFinalOutcome,
  prepareTravelEventBuilderFormOptions,
  applyTravelEventBuilderFormDataToDraft,
  prepareTravelEventBuilderRoundEditorState,
  applyTravelEventBuilderRoundFormDataToDraft,
  prepareTravelEventBuilderPreview
} from "./helpers/travel-event-builder.js";
import {
  advanceShipTravelEventRound,
  applyTravelStagedEffect,
  applyTravelStagedEffects,
  clearShipTravelEvent,
  completeShipTravelEvent,
  getActiveShipTravelEvent,
  getCurrentShipTravelRound,
  getShipTravelEventState,
  previewTravelStagedEffectApplication,
  recordShipTravelStationResult,
  startShipTravelEvent
} from "./helpers/ship-travel-event-state.js";
import { getInstallValidationWarnings, previewComponentInstall, previewInstallValidation, shouldBlockInstall } from "./helpers/install-validation-preview.js";
import { clearStationActionHistory, executeStationAction, getStationActionRollOptions, getStationActionState, previewStationAction, previewStationActionRoll, resolveAssignedActorStatistic, rollStationAction } from "./helpers/station-action-execution.js";
import { getPf2eRollTotal, getPf2eStatisticCandidateKeys, isRollablePf2eStatistic, normalizePf2eStatisticKey, resolvePf2eActorStatistic, rollPf2eStatistic } from "./helpers/pf2e-statistics.js";
import {
  backfillInstallStateForAllShips,
  backfillInstallStateForShip,
  createInstallId,
  deactivateInstallRecord,
  deactivateInstallRecordsByComponent,
  findInstallRecord,
  findShipsMissingInstallState,
  getActiveInstallRecords,
  getInactiveInstallRecords,
  getInstalledComponents,
  getInstallState,
  prepareInstallStateSummary,
  recordInstallState,
  removeInstallState
} from "./helpers/install-state.js";
import {
  TRAVEL_EVENT_BUILDER_IO_VERSION,
  exportTravelEventDraftToJson,
  importTravelEventDraftFromJson,
  importTravelEventDraftFromData,
  exportFinalTravelEventToJson,
  parseTravelEventBuilderJson,
  prepareTravelEventBuilderExportPreview
} from "./helpers/travel-event-builder-io.js";

function isArcflightVehicle(actor) {
  return actor?.type === "vehicle"
    && actor.getFlag?.(ARCFLIGHT.MODULE_ID, "enabled") === true
    && actor.getFlag?.(ARCFLIGHT.MODULE_ID, "actorType") === ARCFLIGHT_SHIP_ACTOR_TYPE;
}

async function setArcflightVehicleEnabled(actor, enabled = true) {
  if (actor?.type !== "vehicle" || typeof actor.setFlag !== "function") {
    throw new Error("Arcflight ships must be PF2E vehicle actors.");
  }

  if (!enabled) {
    return actor.setFlag(ARCFLIGHT.MODULE_ID, "enabled", false);
  }

  return actor.update({
    [`flags.${ARCFLIGHT.MODULE_ID}.enabled`]: true,
    [`flags.${ARCFLIGHT.MODULE_ID}.actorType`]: ARCFLIGHT_SHIP_ACTOR_TYPE,
    [`flags.${ARCFLIGHT.MODULE_ID}.system`]: getArcflightShipData(actor)
  });
}

Hooks.once("init", () => {
  console.log("Arcflight | Initializing module");

  CONFIG.arcflight = Object.freeze({
    constants: ARCFLIGHT,
    createItem: createArcflightItem,
    createCoreHull,
    createHull,
    createCoreArkengine,
    createCoreArkengineMod,
    createCoreCrewAsset,
    createArkengine,
    createArkengineMod,
    createCrewAsset,
    createCoreRoom,
    createRoom,
    createCoreWeapon,
    createWeapon,
    createCoreShipUpgrade,
    createShipUpgrade,
    getCoreHull,
    getCoreArkengine,
    getCoreArkengineMod,
    getCoreCrewAsset,
    getCoreRoom,
    getCoreShipUpgrade,
    getCoreWeapon,
    getCoreHullPlatformKeys,
    getCoreArkengineKeys,
    getHullPatternKeys,
    getHullPattern,
    getArkenginePatternKeys,
    getArkenginePattern,
    getCoreArkengineModKeys,
    getCoreCrewAssetKeys,
    getCoreRoomKeys,
    getCoreShipUpgradeKeys,
    getCoreWeaponKeys,
    getArkengineVariantKeys,
    getArkengineVariant,
    getArkengineVariants,
    getStationKeys,
    getStation,
    getStations,
    getCoreStationAction,
    getCoreStationActionKeys,
    getCoreStationActions,
    getCoreStationActionsForStation,
    getStationActionOutcome,
    previewStationActionOutcome,
    getStationActionState,
    previewStationAction,
    getStationActionRollOptions,
    previewStationActionRoll,
    normalizePf2eStatisticKey,
    getPf2eStatisticCandidateKeys,
    resolvePf2eActorStatistic,
    isRollablePf2eStatistic,
    getPf2eRollTotal,
    rollPf2eStatistic,
    resolveAssignedActorStatistic,
    rollStationAction,
    executeStationAction,
    clearStationActionHistory,
    CORE_HULL_PLATFORM_KEYS,
    CORE_ARKENGINE_KEYS,
    HULL_PATTERN_KEYS,
    ARKENGINE_PATTERN_KEYS,
    CORE_ARKENGINE_MOD_KEYS,
    ARCFLIGHT_ITEM_FOLDER_ROOT,
    arcflightComponentFolderNames,
    arcflightItemFolderNames,
    createArcflightItemFolders,
    findMissingCoreArcflightItems,
    syncCoreArcflightItems,
    findDuplicateArcflightItems,
    cleanupDuplicateArcflightItems,
    organizeArcflightItems,
    CORE_CREW_ASSET_KEYS,
    CORE_ROOM_KEYS,
    CORE_WEAPON_KEYS,
    CORE_SHIP_UPGRADE_KEYS,
    ARKENGINE_VARIANT_KEYS,
    STATION_KEYS,
    CORE_STATION_ACTION_KEYS,
    CORE_TRAVEL_EVENTS,
    CORE_TRAVEL_EVENT_KEYS,
    getCoreTravelEvent,
    getCoreTravelEventKeys,
    getCoreTravelEvents,
    getCoreTravelEventsByCategory,
    EXAMPLE_SHIP_BUILD_KEYS,
    exampleShipBuildKeys: EXAMPLE_SHIP_BUILD_KEYS,
    coreHulls: CORE_HULLS,
    coreArkengines: CORE_ARKENGINES,
    hullPatterns: HULL_PATTERNS,
    arkenginePatterns: ARKENGINE_PATTERNS,
    coreArkengineMods: CORE_ARKENGINE_MODS,
    coreCrewAssets: CORE_CREW_ASSETS,
    coreRooms: CORE_ROOMS,
    coreShipUpgrades: CORE_SHIP_UPGRADES,
    coreWeapons: CORE_WEAPONS,
    arkengineVariants: ARKENGINE_VARIANTS,
    coreStations: CORE_STATIONS,
    coreStationActions: CORE_STATION_ACTIONS,
    coreHullPlatformKeys: CORE_HULL_PLATFORM_KEYS,
    coreArkengineKeys: CORE_ARKENGINE_KEYS,
    hullPatternKeys: HULL_PATTERN_KEYS,
    arkenginePatternKeys: ARKENGINE_PATTERN_KEYS,
    coreArkengineModKeys: CORE_ARKENGINE_MOD_KEYS,
    coreCrewAssetKeys: CORE_CREW_ASSET_KEYS,
    coreRoomKeys: CORE_ROOM_KEYS,
    coreShipUpgradeKeys: CORE_SHIP_UPGRADE_KEYS,
    coreWeaponKeys: CORE_WEAPON_KEYS,
    arkengineVariantKeys: ARKENGINE_VARIANT_KEYS,
    stationKeys: STATION_KEYS,
    coreStationActionKeys: CORE_STATION_ACTION_KEYS,
    coreTravelEvents: CORE_TRAVEL_EVENTS,
    coreTravelEventKeys: CORE_TRAVEL_EVENT_KEYS,
    getItemDocumentType: getArcflightItemDocumentType,
    getDefaultComponentData: getDefaultArcflightComponentData,
    getDefaultShipData: getDefaultArcflightShipData,
    isArcflightItem,
    getComponentType,
    getComponentData,
    getComponentRefitPressure,
    getComponentTierMetadata,
    previewInstallValidation,
    previewComponentInstall,
    getInstallValidationWarnings,
    shouldBlockInstall,
    createInstallId,
    deactivateInstallRecord,
    deactivateInstallRecordsByComponent,
    getActiveInstallRecords,
    getInactiveInstallRecords,
    getInstalledComponents,
    getInstallState,
    recordInstallState,
    removeInstallState,
    findInstallRecord,
    prepareInstallStateSummary,
    findShipsMissingInstallState,
    backfillInstallStateForShip,
    backfillInstallStateForAllShips,
    TRAVEL_EVENT_BUILDER_IO_VERSION,
    exportTravelEventDraftToJson,
    importTravelEventDraftFromJson,
    importTravelEventDraftFromData,
    exportFinalTravelEventToJson,
    parseTravelEventBuilderJson,
    prepareTravelEventBuilderExportPreview,
    isArcflightVehicle,
    setArcflightVehicleEnabled,
    setHullPattern,
    setArkenginePattern,
    addCrewAsset,
    removeCrewAsset,
    removeInstalledArkengineMod,
    removeInstalledCrewAsset,
    removeInstalledRoom,
    removeInstalledShipUpgrade,
    removeInstalledWeapon,
    installHull,
    installHullOnShip,
    installArkengine,
    installArkengineMod,
    installArkengineModOnShip,
    installArkengineOnShip,
    installRoom,
    installRoomOnShip,
    installShipUpgrade,
    installShipUpgradeOnShip,
    installWeapon,
    installWeaponOnShip,
    recalculateShipStats,
    calculateDerivedShipStats,
    calculateRefitPressure,
    updateShipTierState,
    getShipTierState,
    getShipRefitPressure,
    getShipRefitStatus,
    getShipActionEconomy,
    getShipTravelResources,
    previewShipTravelResourceChange,
    updateShipTravelResources,
    getTravelStationKeys,
    isTravelStationKey,
    getTravelFiveStationKeys,
    normalizeTravelDegree,
    getTravelDegreeContribution,
    getTravelRoundOutcome,
    getTravelEventOutcome,
    validateTravelEventDefinition,
    TRAVEL_EVENT_TEMPLATE_VERSION,
    createBlankTravelEventTemplate,
    createBlankTravelRoundTemplate,
    createBlankStationPromptTemplate,
    createBlankRollFeedbackTemplate,
    createBlankOutcomeBranchesTemplate,
    createBlankFinalOutcomesTemplate,
    getTravelEventAuthoringGuidelines,
    validateTravelEventAuthoringTemplate,
    TRAVEL_EVENT_BUILDER_VERSION,
    createTravelEventDraft,
    normalizeTravelEventDraft,
    validateTravelEventDraft,
    finalizeTravelEventDraft,
    cloneTravelEventToDraft,
    createTravelBuilderResourceEffect,
    createTravelBuilderRound,
    createTravelBuilderStationPrompt,
    createTravelBuilderOutcomeBranch,
    createTravelBuilderFinalOutcome,
    prepareTravelEventBuilderFormOptions,
    applyTravelEventBuilderFormDataToDraft,
    prepareTravelEventBuilderRoundEditorState,
    applyTravelEventBuilderRoundFormDataToDraft,
    prepareTravelEventBuilderPreview,
    prepareTravelEventSummary,
    prepareTravelRoundSummary,
    getTravelEventStationPrompt,
    getShipTravelEventState,
    getActiveShipTravelEvent,
    startShipTravelEvent,
    recordShipTravelStationResult,
    getCurrentShipTravelRound,
    advanceShipTravelEventRound,
    previewTravelStagedEffectApplication,
    applyTravelStagedEffect,
    applyTravelStagedEffects,
    completeShipTravelEvent,
    clearShipTravelEvent,
    ArcflightTravelEventBuilder,
    openTravelEventBuilder,
    prepareTravelEventBuilderShellState,
    ArcflightTravelEventRunner,
    openTravelEventRunner,
    prepareTravelEventLibraryOptions,
    prepareSelectedTravelEventLibraryDetails,
    prepareTravelEventNarrativeLog,
    resetShipActionEconomy,
    spendShipActionPoints,
    canSpendShipActionPoints,
    assignStation,
    clearStationAssignment,
    clearStationAssignments,
    clearShipBuild,
    clearInstalledRooms,
    clearInstalledShipUpgrades,
    clearInstalledArkengineMods,
    clearCrewRoster,
    clearComponentPatterns,
    assignShipStation: assignStation,
    clearShipStation: clearStationAssignment,
    getExampleShipBuildKeys,
    getExampleShipBuild,
    applyExampleShipBuild,
    applyCleanExampleShipBuild,
    runFrameworkSmokeTest,
    getShipData: getArcflightShipData,
    componentDefaults: arcflightComponentDefaults,
    shipDefaults: arcflightShipDefaults,
    itemFolderRoot: ARCFLIGHT_ITEM_FOLDER_ROOT,
    itemFolderNames: arcflightItemFolderNames,
    componentFolderNames: arcflightComponentFolderNames,
    createItemFolders: createArcflightItemFolders,
    organizeArcflightItems,
    findMissingCoreArcflightItems,
    syncCoreArcflightItems,
    findDuplicateItems: findDuplicateArcflightItems,
    cleanupDuplicateItems: cleanupDuplicateArcflightItems,
    findDuplicateArcflightItems,
    cleanupDuplicateArcflightItems,
    devTools: createArcflightDevTools()
  });

  game.arcflight = CONFIG.arcflight;

  registerArcflightSheets().catch((error) => {
    console.warn("Arcflight | Sheet registration failed; continuing startup.", error);
  });
});

export {
  ARCFLIGHT,
  createArcflightItem,
  createCoreHull,
  createHull,
  createCoreArkengine,
  createCoreArkengineMod,
  createCoreCrewAsset,
  createArkengine,
  createArkengineMod,
  createCrewAsset,
  createCoreRoom,
  createRoom,
  createCoreWeapon,
  createWeapon,
  createCoreShipUpgrade,
  createShipUpgrade,
  getCoreHull,
  getCoreArkengine,
  getCoreArkengineMod,
  getCoreCrewAsset,
  getCoreRoom,
  getCoreShipUpgrade,
  getCoreWeapon,
  getCoreHullPlatformKeys,
  getCoreArkengineKeys,
  getHullPatternKeys,
  getHullPattern,
  getArkenginePatternKeys,
  getArkenginePattern,
  getCoreArkengineModKeys,
  getCoreCrewAssetKeys,
  getCoreRoomKeys,
  getCoreShipUpgradeKeys,
  getCoreWeaponKeys,
  getArkengineVariantKeys,
  getArkengineVariant,
  getArkengineVariants,
  getStationKeys,
  getStation,
  getStations,
  getCoreStationAction,
  getCoreStationActionKeys,
  getCoreStationActions,
  getCoreStationActionsForStation,
  getStationActionOutcome,
  previewStationActionOutcome,
  getStationActionState,
  previewStationAction,
  getStationActionRollOptions,
  previewStationActionRoll,
  normalizePf2eStatisticKey,
  getPf2eStatisticCandidateKeys,
  resolvePf2eActorStatistic,
  isRollablePf2eStatistic,
  getPf2eRollTotal,
  rollPf2eStatistic,
  resolveAssignedActorStatistic,
  rollStationAction,
  executeStationAction,
  clearStationActionHistory,
  CORE_HULLS,
  CORE_ARKENGINES,
  HULL_PATTERNS,
  ARKENGINE_PATTERNS,
  CORE_ARKENGINE_MODS,
  CORE_CREW_ASSETS,
  CORE_ROOMS,
  CORE_SHIP_UPGRADES,
  CORE_WEAPONS,
  ARKENGINE_VARIANTS,
  CORE_HULL_PLATFORM_KEYS,
  CORE_ARKENGINE_KEYS,
  HULL_PATTERN_KEYS,
  ARKENGINE_PATTERN_KEYS,
  CORE_ARKENGINE_MOD_KEYS,
  ARCFLIGHT_ITEM_FOLDER_ROOT,
  arcflightComponentFolderNames,
  arcflightItemFolderNames,
  createArcflightItemFolders,
  findMissingCoreArcflightItems,
  syncCoreArcflightItems,
  findDuplicateArcflightItems,
  cleanupDuplicateArcflightItems,
  organizeArcflightItems,
  CORE_CREW_ASSET_KEYS,
  CORE_ROOM_KEYS,
  CORE_SHIP_UPGRADE_KEYS,
  CORE_WEAPON_KEYS,
  ARKENGINE_VARIANT_KEYS,
  CORE_STATIONS,
  STATION_KEYS,
  CORE_STATION_ACTIONS,
  CORE_STATION_ACTION_KEYS,
  CORE_TRAVEL_EVENTS,
  CORE_TRAVEL_EVENT_KEYS,
  getCoreTravelEvent,
  getCoreTravelEventKeys,
  getCoreTravelEvents,
  getCoreTravelEventsByCategory,
  EXAMPLE_SHIP_BUILD_KEYS,
  getExampleShipBuildKeys,
  getExampleShipBuild,
  applyExampleShipBuild,
  applyCleanExampleShipBuild,
  addCrewAsset,
  removeCrewAsset,
  removeInstalledArkengineMod,
  removeInstalledCrewAsset,
  removeInstalledRoom,
  removeInstalledShipUpgrade,
  removeInstalledWeapon,
  isArcflightVehicle,
  setArcflightVehicleEnabled,
  setHullPattern,
  setArkenginePattern,
  installArkengine,
  installArkengineMod,
  installArkengineModOnShip,
  installArkengineOnShip,
  installHull,
  installHullOnShip,
  installRoom,
  installRoomOnShip,
  installShipUpgrade,
  installShipUpgradeOnShip,
  installWeapon,
  installWeaponOnShip,
  recalculateShipStats,
  calculateDerivedShipStats,
  calculateRefitPressure,
  updateShipTierState,
  getShipTierState,
  getShipActionEconomy,
  getShipTravelResources,
  previewShipTravelResourceChange,
  updateShipTravelResources,
  getTravelStationKeys,
  isTravelStationKey,
  getTravelFiveStationKeys,
  normalizeTravelDegree,
  getTravelDegreeContribution,
  getTravelRoundOutcome,
  getTravelEventOutcome,
  validateTravelEventDefinition,
  TRAVEL_EVENT_TEMPLATE_VERSION,
  createBlankTravelEventTemplate,
  createBlankTravelRoundTemplate,
  createBlankStationPromptTemplate,
  createBlankRollFeedbackTemplate,
  createBlankOutcomeBranchesTemplate,
  createBlankFinalOutcomesTemplate,
  getTravelEventAuthoringGuidelines,
  validateTravelEventAuthoringTemplate,
  TRAVEL_EVENT_BUILDER_VERSION,
  createTravelEventDraft,
  normalizeTravelEventDraft,
  validateTravelEventDraft,
  finalizeTravelEventDraft,
  cloneTravelEventToDraft,
  createTravelBuilderResourceEffect,
  createTravelBuilderRound,
  createTravelBuilderStationPrompt,
  createTravelBuilderOutcomeBranch,
  createTravelBuilderFinalOutcome,
  prepareTravelEventBuilderFormOptions,
  applyTravelEventBuilderFormDataToDraft,
  prepareTravelEventBuilderRoundEditorState,
  applyTravelEventBuilderRoundFormDataToDraft,
  prepareTravelEventBuilderPreview,
  prepareTravelEventSummary,
  prepareTravelRoundSummary,
  getTravelEventStationPrompt,
  getShipTravelEventState,
  getActiveShipTravelEvent,
  startShipTravelEvent,
  recordShipTravelStationResult,
  getCurrentShipTravelRound,
  advanceShipTravelEventRound,
  previewTravelStagedEffectApplication,
  applyTravelStagedEffect,
  applyTravelStagedEffects,
  completeShipTravelEvent,
  clearShipTravelEvent,
  ArcflightTravelEventBuilder,
  openTravelEventBuilder,
  prepareTravelEventBuilderShellState,
  ArcflightTravelEventRunner,
  openTravelEventRunner,
  prepareTravelEventLibraryOptions,
  prepareSelectedTravelEventLibraryDetails,
  prepareTravelEventNarrativeLog,
  resetShipActionEconomy,
  spendShipActionPoints,
  canSpendShipActionPoints,
  getShipRefitPressure,
  getShipRefitStatus,
  assignStation,
  clearStationAssignment,
  clearStationAssignments,
  clearShipBuild,
  clearInstalledRooms,
  clearInstalledShipUpgrades,
  clearInstalledArkengineMods,
  clearCrewRoster,
  clearComponentPatterns,
  runFrameworkSmokeTest,
  getArcflightItemDocumentType,
  isArcflightItem,
  getComponentType,
  getComponentData,
  getComponentRefitPressure,
  getComponentTierMetadata,
  previewInstallValidation,
  previewComponentInstall,
  getInstallValidationWarnings,
  shouldBlockInstall,
  backfillInstallStateForAllShips,
  backfillInstallStateForShip,
  createInstallId,
  deactivateInstallRecord,
  deactivateInstallRecordsByComponent,
  getActiveInstallRecords,
  getInactiveInstallRecords,
  getInstalledComponents,
  getInstallState,
  recordInstallState,
  removeInstallState,
  findInstallRecord,
  prepareInstallStateSummary,
  findShipsMissingInstallState,
  TRAVEL_EVENT_BUILDER_IO_VERSION,
  exportTravelEventDraftToJson,
  importTravelEventDraftFromJson,
  importTravelEventDraftFromData,
  exportFinalTravelEventToJson,
  parseTravelEventBuilderJson,
  prepareTravelEventBuilderExportPreview,
  getDefaultArcflightComponentData,
  arcflightComponentDefaults,
  ARCFLIGHT_SHIP_ACTOR_TYPE,
  arcflightShipDefaults,
  getArcflightShipData,
  getDefaultArcflightShipData
};
