import test from "node:test";
import assert from "node:assert/strict";
import { launchVoyageEventSession } from "../../../scripts/voyage/foundry/event-launcher.js";
import { getM12EventDefinition, M12_DEFINITION_SNAPSHOT_ID, M12_EVENT_ID, M12_FOCUS_ABILITIES } from "../../../scripts/voyage/m12/event-definition.js";
import { getFoundrySessionMutationCoordinator } from "../../../scripts/voyage/foundry/session-coordinator.js";
import { executeVoyagePlayerIntent, registerVoyageGmCommandTransport } from "../../../scripts/voyage/foundry/gm-command-transport.js";
import { beginVoyageEventSessionResolution, correctVoyageEventSession, dispatchVoyageEventSessionCommand, readVoyageEventSessionMultiplayerProjection, readVoyageEventSessionResolution, reloadVoyageEventSession, resolveVoyageEventSessionStation } from "../../../scripts/voyage/foundry/event-session-runtime.js";

const actor = (id, type = "character") => ({ id, uuid: `Actor.${id}`, name: id, type, getFlag: () => true });
function fixture() {
  const journals = [], tracker = { creates: 0, updates: 0, gmDocumentWrites: 0, playerDocumentWrites: 0, focusCalls: 0, stationCalls: 0 };
  const document = (data, shared = null, origin = "gm") => { const source = shared ?? { _id: data._id, flags: structuredClone(data.flags), name: "Session", pages: [] }; const entry = { id: source._id, __testSource: source, toObject: () => structuredClone(source), async update(payload) { tracker.updates += 1; tracker[origin === "player" ? "playerDocumentWrites" : "gmDocumentWrites"] += 1; source.flags.arcflight.system.voyageSession = structuredClone(payload["flags.arcflight.system.voyageSession"]); return this; }, async delete() { journals.splice(journals.indexOf(entry), 1); } }; return entry; };
  const actors = [actor("ship-1", "vehicle"), actor("captain"), actor("engineer"), actor("navigator")]; actors[0].getFlag = (_module, key) => key === "enabled" ? true : "arcflightShip";
  const context = { authenticatedUserId: "gm-1", authenticatedConnectionId: "connection-gm-1", trustedTransportContext: true, activeGmUserId: "gm-1", users: [{ id: "gm-1", isGM: true, active: true }], actors, journalEntries: journals, createDocumentId: () => "Journal.slice-j", createVoyageTimestamp: () => "2026-08-13T12:00:00.000Z", JournalEntry: { async create(data) { tracker.creates += 1; const entry = document(data); journals.push(entry); return entry; } }, isJournalEntryDocument: () => true, resolveEventDefinitionSnapshot: async () => getM12EventDefinition(), async runExclusiveSessionMutation(_descriptor, callback) { return callback({ connectionId: "connection-gm-1", occurredAt: "2026-08-13T12:00:00.000Z" }); }, executeVoyagePf2ePendingCheck: async (pending) => { tracker.stationCalls += 1; return { ok: true, status: "rolled", pendingCheckId: pending.pendingCheckId, sequence: pending.sequence, sourceKind: "character", sourceUuid: pending.source.uuid, statisticSlug: pending.statisticSlugOrAbilityId, dc: pending.finalDc, rollMode: "public", result: { total: pending.finalDc, degreeOfSuccess: 2, degreeOfSuccessSlug: "success" }, errors: [], warnings: [] }; }, executeVoyagePf2eFocusCheck: async (pending) => { tracker.focusCalls += 1; return { ok: true, status: "rolled", pendingCheckId: pending.pendingCheckId, sequence: pending.sequence, sourceKind: "character", sourceUuid: pending.source.uuid, statisticSlug: pending.statisticSlugOrAbilityId, dc: pending.finalDc, rollMode: "public", result: { total: pending.finalDc, degreeOfSuccess: 2, degreeOfSuccessSlug: "success" }, errors: [], warnings: [] }; } };
  return { context, journals, tracker };
}
function playerContext(fx, userId, connectionId, operatorId) {
  const journalEntries = fx.journals.map((entry) => { const source = entry.__testSource; return { id: source._id, __testSource: source, toObject: () => structuredClone(source), async update(payload) { fx.tracker.updates += 1; fx.tracker.playerDocumentWrites += 1; source.flags.arcflight.system.voyageSession = structuredClone(payload["flags.arcflight.system.voyageSession"]); return this; }, async delete() {} }; });
  return { ...fx.context, authenticatedUserId: userId, authenticatedConnectionId: connectionId, journalEntries, users: [{ id: "gm-1", isGM: true, active: true }, { id: userId, isGM: false, active: true }], resolveVoyageOperatorForPrincipal: () => [{ kind: "actor", id: operatorId, uuid: `Actor.${operatorId}`, name: operatorId }] };
}
function transportedPlayer(fx, userId, connectionId, operatorId) {
  const game = { user: { id: "gm-1", isGM: true, active: true }, users: [{ id: "gm-1", isGM: true, active: true }, { id: userId, isGM: false, active: true }], socket: { id: "gm-transport", on: () => {}, emit: () => {} }, time: { serverTime: Date.parse("2026-08-13T12:00:00.000Z") } };
  const context = { ...playerContext(fx, userId, connectionId, operatorId), journalEntries: fx.journals, authenticatedConnectionId: "gm-transport", trustedTransportContext: true, activeGmUserId: "gm-1", __trustedRemotePlayerIntent: true, executingGmUserId: "gm-1", runExclusiveSessionMutation: getFoundrySessionMutationCoordinator(game) };
  let handler; const socket = { register: (_name, callback) => { handler = callback; }, async executeAsGM(_name, request) { return handler.call({ socketdata: { userId } }, request); } };
  registerVoyageGmCommandTransport({ socketlib: { registerModule: () => socket }, onIntent: async (request, origin) => { fx.transportSenderIds ??= []; fx.transportSenderIds.push(origin.originatingUserId); fx.transportExecutingUserIds ??= []; fx.transportExecutingUserIds.push(context.executingGmUserId); return request.kind === "voyage.m12-resolve-station" ? resolveVoyageEventSessionStation(request, context) : dispatchVoyageEventSessionCommand(request, context); } });
  return { socket };
}

test("M12 Slice J full multiplayer Task 4 acceptance reaches Awaiting Round Closeout through GM transport", async () => {
  const fx = fixture(); fx.context.focusAbilities = [...M12_FOCUS_ABILITIES]; const sessionId = "slice-j-acceptance";
  const launched = await launchVoyageEventSession({ kind: "voyage.m12-launch-event", requestId: "slice-j-launch", sessionId, expectedRevision: 0, authorityEpoch: 0, eventId: M12_EVENT_ID, definitionSnapshotId: M12_DEFINITION_SNAPSHOT_ID, shipId: "ship-1", operatorSelections: { captain: "captain", engineer: "engineer", navigator: "navigator" } }, fx.context); assert.equal(launched.ok, true, JSON.stringify(launched.errors));
  const playerA = playerContext(fx, "player-a", "connection-a", "captain"), playerB = playerContext(fx, "player-b", "connection-b", "engineer"), playerC = playerContext(fx, "player-c", "connection-c", "navigator"); const transportA = transportedPlayer(fx, "player-a", "connection-a", "captain"), transportB = transportedPlayer(fx, "player-b", "connection-b", "engineer"), transportC = transportedPlayer(fx, "player-c", "connection-c", "navigator");
  const crew = { ...fx.context, authenticatedUserId: "crew", authenticatedConnectionId: "connection-crew", users: [{ id: "gm-1", isGM: true, active: true }, { id: "crew", isGM: false, active: true }], resolveVoyageOperatorForPrincipal: () => ({ kind: "actor", id: "unassigned", uuid: "Actor.unassigned", name: "unassigned" }) }; const observer = { ...crew, authenticatedUserId: "observer", authenticatedConnectionId: "connection-observer", users: [...crew.users, { id: "observer", isGM: false, active: true }], resolveVoyageOperatorForPrincipal: () => [] }; const read = (context, requestId, expectedRevision) => readVoyageEventSessionMultiplayerProjection({ kind: "voyage.m12-read-multiplayer-projection", requestId, sessionId, expectedRevision }, context);
  assert.equal(read(fx.context, "slice-j-gm-read", launched.revision).ok, true); assert.equal(read(playerA, "slice-j-player-read", launched.revision).projection.projectionRole, "operator"); assert.equal(read(crew, "slice-j-crew-read", launched.revision).projection.projectionRole, "crew"); assert.equal(read(observer, "slice-j-observer-read", launched.revision).projection.projectionRole, "observer"); assert.equal(Object.hasOwn(read(playerA, "slice-j-private-read", launched.revision).projection, "processedRequests"), false);
  let revision = launched.revision;
  let result = await dispatchVoyageEventSessionCommand({ kind: "voyage.m11-command", requestId: "slice-j-begin-planning", sessionId, expectedRevision: revision, authorityEpoch: 0, commandKind: "begin-crew-planning", payload: { phaseStartSnapshotId: "slice-j-begin-planning" } }, fx.context);
  assert.equal(result.ok, true, JSON.stringify(result.errors));
  revision = result.revision;
  const select = async (requestId, stationId, actionId, riskBidId = null) => dispatchVoyageEventSessionCommand({ kind: "voyage.m11-command", requestId, sessionId, expectedRevision: revision, authorityEpoch: 0, commandKind: "station-selection", payload: { stationId, actionId, approachId: `${actionId}-approach`, riskBidId } }, fx.context);
  result = await select("slice-j-captain", "captain", "captain-round-1-action-3", "captain-round-1-action-3-risk-2"); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision; result = await select("slice-j-engineer", "engineer", "engineer-round-1-action-1"); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision; result = await select("slice-j-navigator", "navigator", "navigator-round-1-action-1"); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision;
  result = await dispatchVoyageEventSessionCommand({ kind: "voyage.m11-command", requestId: "slice-j-order", sessionId, expectedRevision: revision, authorityEpoch: 0, commandKind: "station-order", payload: { stationOrder: ["captain", "engineer", "navigator"] } }, fx.context); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision; result = await dispatchVoyageEventSessionCommand({ kind: "voyage.m11-command", requestId: "slice-j-lock", sessionId, expectedRevision: revision, authorityEpoch: 0, commandKind: "plan-lock", payload: { phaseStartSnapshotId: "slice-j-lock" } }, fx.context); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision; assert.equal(reloadVoyageEventSession(sessionId, fx.context).ok, true);
  result = await correctVoyageEventSession({ kind: "voyage.m11-correct-session", requestId: "slice-j-unlock", sessionId, expectedRevision: revision, authorityEpoch: 0, correctionKind: "plan-unlock", targetRequestId: null, targetCheckpointId: null, replacementPayload: {}, reason: "integration correction", confirmation: true }, fx.context); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision; result = await select("slice-j-edit", "engineer", "engineer-round-1-action-2"); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision; result = await dispatchVoyageEventSessionCommand({ kind: "voyage.m11-command", requestId: "slice-j-relock", sessionId, expectedRevision: revision, authorityEpoch: 0, commandKind: "plan-lock", payload: { phaseStartSnapshotId: "slice-j-relock" } }, fx.context); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision; result = await beginVoyageEventSessionResolution({ kind: "voyage.m12-begin-resolution", requestId: "slice-j-begin", sessionId, expectedRevision: revision, authorityEpoch: 0 }, fx.context); assert.equal(result.ok, true, JSON.stringify(result.errors)); revision = result.revision;
  const directWrites = fx.tracker.gmDocumentWrites + fx.tracker.playerDocumentWrites; const reactionId = readVoyageEventSessionResolution(sessionId, fx.context).projection.reactionWindow.opportunities[0].reactionId;
  result = await dispatchVoyageEventSessionCommand({ kind: "voyage.m11-command", requestId: "slice-j-direct-focus", sessionId, expectedRevision: revision, authorityEpoch: 0, commandKind: "focus-reaction-use", payload: { reactionId } }, playerA); assert.equal(result.ok, false); assert.equal(result.errors[0].code, "m11-cross-client-coordinator-required"); assert.equal(fx.tracker.gmDocumentWrites + fx.tracker.playerDocumentWrites, directWrites); assert.equal(fx.tracker.focusCalls, 0);

  let gmWrites = fx.tracker.gmDocumentWrites; result = await executeVoyagePlayerIntent({ kind: "voyage.m11-command", requestId: "slice-j-focus", sessionId, expectedRevision: revision, authorityEpoch: 0, commandKind: "focus-reaction-use", payload: { reactionId } }, transportA.socket); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(fx.tracker.focusCalls, 1); assert.equal(fx.tracker.gmDocumentWrites, gmWrites + 3); assert.equal(fx.tracker.playerDocumentWrites, 0); revision = result.revision; assert.equal(fx.transportSenderIds.at(-1), "player-a"); assert.equal(fx.transportExecutingUserIds.at(-1), "gm-1"); assert.notEqual(fx.transportSenderIds.at(-1), fx.transportExecutingUserIds.at(-1));
  const postFocusProjection = readVoyageEventSessionResolution(sessionId, fx.context).projection; assert.equal(postFocusProjection.reactionWindowOpen, false); const currentStation = postFocusProjection.stations.find((entry) => entry.current); assert.equal(currentStation?.stationId, "captain"); assert.equal(currentStation?.canRoll, true);
  result = await resolveVoyageEventSessionStation({ kind: "voyage.m12-resolve-station", requestId: "slice-j-direct-station", sessionId, expectedRevision: revision, authorityEpoch: 0 }, playerA); assert.equal(result.ok, false); assert.equal(result.errors[0].code, "m11-cross-client-coordinator-required"); assert.equal(fx.tracker.gmDocumentWrites + fx.tracker.playerDocumentWrites, directWrites + 3); assert.equal(fx.tracker.stationCalls, 0);
  const foreign = await executeVoyagePlayerIntent({ kind: "voyage.m12-resolve-station", requestId: "slice-j-foreign", sessionId, expectedRevision: revision, authorityEpoch: 0 }, transportB.socket); assert.equal(foreign.ok, false); assert.equal(foreign.errors[0].code, "m11-projection-not-authorized"); assert.equal(fx.tracker.stationCalls, 0);
  const roll = async (transport, requestId) => executeVoyagePlayerIntent({ kind: "voyage.m12-resolve-station", requestId, sessionId, expectedRevision: revision, authorityEpoch: 0 }, transport.socket);
  gmWrites = fx.tracker.gmDocumentWrites; result = await roll(transportA, "slice-j-captain-roll"); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(fx.tracker.stationCalls, 1); assert.equal(fx.tracker.gmDocumentWrites, gmWrites + 1); assert.equal(fx.tracker.playerDocumentWrites, 0); revision = result.revision;
  gmWrites = fx.tracker.gmDocumentWrites; result = await roll(transportB, "slice-j-engineer-roll"); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(fx.tracker.stationCalls, 2); assert.equal(fx.tracker.gmDocumentWrites, gmWrites + 1); assert.equal(fx.tracker.playerDocumentWrites, 0); revision = result.revision;
  gmWrites = fx.tracker.gmDocumentWrites; result = await roll(transportC, "slice-j-navigator-roll"); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(fx.tracker.stationCalls, 3); assert.equal(fx.tracker.gmDocumentWrites, gmWrites + 1); assert.equal(fx.tracker.playerDocumentWrites, 0); revision = result.revision;
  assert.equal(new Set(fx.transportSenderIds.slice(-4)).size >= 3, true); assert.equal(fx.transportSenderIds.slice(-4).every((id, index) => fx.transportExecutingUserIds.at(-(4 - index)) === "gm-1"), true); assert.equal(reloadVoyageEventSession(sessionId, fx.context).ok, true);
  const finalProjection = read(fx.context, "slice-j-final-read", revision).projection; assert.equal(finalProjection.resolutionComplete, true); assert.equal(finalProjection.sessionState, "station-resolution"); assert.equal(finalProjection.phase, "resolution"); const stored = fx.journals[0].__testSource.flags.arcflight.system.voyageSession; assert.equal(stored.encounterState.momentum, 0); assert.deepEqual(stored.encounterState.activeHazards, []); assert.equal(fx.tracker.playerDocumentWrites, 0); assert.equal(fx.tracker.focusCalls, 1); assert.equal(fx.tracker.stationCalls, 3);
});
